### ISSUE TITLE
[Feature] Enable all button

### ISSUE THREAD

**Issue by MooMcMooman** [BetterDiscord/BetterDiscord#1718] opened 2024-02-04 21:33 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Add a button that enables all of the downloaded plugin (and why not add a disable all button)

**Comment by Riddim-GLiTCH** [comment] 2024-02-04 21:38
This has already been discussed, and from what I hear also already in the works.

**Comment by fowlis** [comment] 2024-02-04 22:46
If this is in relation to doing a repair of BD after it disappears following a Discord update, just use the install option in the installer. It will keep your addons enabled after restart.

**Comment by rauenzi** [comment] 2024-02-22 00:08
Duplicate of #723

**Closed by rauenzi** 2024-02-22 00:08 UTC
Labels: enhancement
