### ISSUE TITLE
[Feature] - Option to sort plugins by status (enabled & disabled)

### ISSUE THREAD

**Issue by BigFlubba** [BetterDiscord/BetterDiscord#1198] opened 2022-02-01 19:27 UTC
I don't know why this is not a thing yet, but nonetheless, I would like the option for there to be a sorting option of enabled plugins and themes and disabled ones. This would help a lot for others (including me) who have more than 20 plugins installed and some enabled and disabled. This would be very helpful.

**Comment by dav1312** [comment] 2022-02-04 14:02
Duplicate of #1037

**Closed** 2022-02-04 17:41 UTC
Labels: enhancement
