### ISSUE TITLE
[Bug] GitHub button wrong redirect

### ISSUE THREAD

**Issue by kkrypt0nn** [BetterDiscord/BetterDiscord#991] opened 2021-08-13 18:06 UTC
**Describe the Bug**
When clicking on the GitHub icon on the installer you get redirected to https://github.com/BetterDiscord/BetterDiscor, which is missing an **d** at the end.

**To Reproduce**
- Download the installer
- Start it
- Click the GitHub icon

**Expected Behavior**
Get redirected to https://github.com/BetterDiscord/BetterDiscord

**Screenshots**
![image](https://user-images.githubusercontent.com/43011723/129401020-f1b149f2-8765-4622-b7c7-81d0f11b26f1.png)
![image](https://user-images.githubusercontent.com/43011723/129401045-b91f4803-d9eb-432d-bc40-93bc5dda187d.png)

**Discord Version**
Canary

**Comment by dav1312** [comment] 2021-08-13 18:09
Duplicate of #945

**Comment by rauenzi** [comment] 2021-08-13 18:25
see above

**Closed by rauenzi** 2021-08-13 18:25 UTC
Labels: bug

**Comment by dashishmeister** [comment] 2021-08-17 12:49
bruh typo
