### ISSUE TITLE
[Bug] Cannot use up/down arrows (or any other keys) to navigate server list on Windows

### ISSUE THREAD

**Issue by Simon818** [BetterDiscord/BetterDiscord#1322] opened 2022-06-22 23:06 UTC
**Describe the Bug**

Pressing the up/down arrow keys in the server list should navigate through the available servers. With Better Discord installed, this no longer works; the arrow keys do nothing at all. As soon as BetterDiscord is uninstalled, this functionality works again.
**To Reproduce**

1. Press f6 until keyboard focus lands on the server list.
2. Try moving through it with the up and down arrows, home, or end.

**Expected Behavior**

The arrow keys should move through the available servers. Home and end should move to the top or bottom of the server list.
**Screenshots**

**Discord Version**

Stable and Canary were both tested.
**Additional Context**

There is a non-0 number of people who rely on the keyboard for navigation, including screen-reader users. Discord has actually put a significant amount of work into keyboard navigation, and based on [this issue](https://github.com/BetterDiscord/BetterDiscord/issues/1223) the arrow keys may not work in other contexts as well.

When I first installed BetterDiscord into Canary, the arrow keys worked in the server list. As soon as I did a ctrl+r to reload Discord, it stopped working and continued to not work. Two other keyboard-using friends have confirmed that it never worked for them.

I have not tested anywhere except Windows 10 (X64) with Discord Canary and Stable.

**Comment by zersiax** [comment] 2022-06-23 15:01
Confirmed, can reproduce on latest BetterDiscord in both regular and Canary versions.

**Comment by Saltssaumure** [comment] 2022-06-24 01:05
I cannot get keyboard focus on server list at all, been using Ctrl+T search to switch servers instead. Definitely not ideal so fix would be much appreciated.

**Comment by rauenzi** [comment] 2022-06-27 16:11
Duplicate of #1223

**Closed by rauenzi** 2022-06-27 16:11 UTC
Labels: bug
