### ISSUE TITLE
[Feature]settings button for themes

### ISSUE THREAD

**Issue by IMrCreepyI** [BetterDiscord/BetterDiscord#1475] opened 2022-11-09 21:31 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

a button to change the settings of a theme instead of having to go in to edit mode.

### Anything else?

it might be easier for some people who don't know what some of the code does (like me).
there used to be a plugin for it but i cant find it anymore. it also had to move the setting to the plugin settings

**Comment by SmolAlli** [comment] 2022-11-09 21:40
This is already a WIP for the developers but there's been no ETA.

**Comment by rauenzi** [comment] 2022-11-09 21:44
I'm not sure how well you searched because there's a duplicate on the first page of issues.

Duplicate of #1173

**Closed by rauenzi** 2022-11-09 21:44 UTC
Labels: enhancement
