### ISSUE TITLE
[Bug] React Spellchecker Issue

### ISSUE THREAD

**Issue by TheRedCmdCraft** [BetterDiscord/BetterDiscord#1568] opened 2023-03-13 14:47 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

![grafik](https://user-images.githubusercontent.com/57496807/224735508-2fb0add3-bb50-4ff3-a3a5-c9115ca9e6e5.png)
![grafik](https://user-images.githubusercontent.com/57496807/224735552-407c91de-7778-4500-84ec-1f0b91d9a835.png)

Discord has been randomly crashed. i had nothing done. i was doing my homework for school on paper and had my pc running with discord opend. i hope the images can help you to find the bug

```
%c[Spellchecker]
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 5/13/2022 10:00 -0800, _f: undefined, _strict: undefined, _locale: [object Object]
Error
at Function.createFromInputFallback (https://discord.com/assets/da438bff819561370309.js:1350:330)
at Bn (https://discord.com/assets/da438bff819561370309.js:1376:696)
at Wn (https://discord.com/assets/da438bff819561370309.js:1379:356)
at Zn (https://discord.com/assets/da438bff819561370309.js:1379:199)
at Yn (https://discord.com/assets/da438bff819561370309.js:1378:886)
at Kn (https://discord.com/assets/da438bff819561370309.js:1379:697)
at zn (https://discord.com/assets/da438bff819561370309.js:1379:731)
at o (https://discord.com/assets/da438bff819561370309.js:1346:961)
at Object.918513 (https://discord.com/assets/40236214a0bc649dcd00.js:21:346)
at l (https://discord.com/assets/5d67886ea6bce8e5a6d8.js:1:154)
at Object.908570 (https://discord.com/assets/40236214a0bc649dcd00.js:14:239)
at l (https://discord.com/assets/5d67886ea6bce8e5a6d8.js:1:154)
at Object.101577 (https://discord.com/assets/40236214a0bc649dcd00.js:2:329)
at l (https://discord.com/assets/5d67886ea6bce8e5a6d8.js:1:154)
at Object.877271 (https://discord.com/assets/800621cfb61dbe56693c.js:353:630)
at l (https://discord.com/assets/5d67886ea6bce8e5a6d8.js:1:154)
at Module.842656 (https://discord.com/assets/4af4a7dc54bbb41d6125.js:42:175)
at Function.l (https://discord.com/assets/5d67886ea6bce8e5a6d8.js:1:154)
[DEPRECATED] Please use `subscribeWithSelector` middleware
%c[NativeDispatchUtils]
3
%c[BetterDiscord]%c [WebpackModules~getModule]%c
undefined
```

### Expected Behavior

no crash

### Steps To Reproduce

i don`t know. this issue was happening while i`m doing my schoolwork on a paper and had discord open

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.5

**Comment by rauenzi** [comment] 2023-03-13 15:33
The crash here looks like a duplicate of #1564

**Comment by TheRedCmdCraft** [comment] 2023-03-13 15:46
yes. I`ve researched and I think this is a issue with the iso datetime. I am not shure if this is caused by a message from a webhook that was send at the same time. In the webhook was an embed with timestamp, but i don`t know if there are any links between the two things

**Comment by onukwilip** [comment] 2023-04-13 17:12
Are you using any other JavaScript bundler to build your React project?

**Closed** 2023-04-15 02:01 UTC
Labels: bug
