### ISSUE TITLE
Failed to inject on latest Discord update[Bug]

### ISSUE THREAD

**Issue by JimDude7404** [BetterDiscord/BetterDiscord#1406] opened 2022-09-27 00:59 UTC
**Describe the Bug**
After the latest Discord update BetterDiscord no longer works

**To Reproduce**
Just update

**Expected Behavior**
Better Discord working

**Screenshots**

**Discord Version** 
Stable

**Additional Context**

**Comment by Strencher** [comment] 2022-09-27 01:00
Duplicate of #1404

**Closed by Strencher** 2022-09-27 01:00 UTC
Labels: bug
