### ISSUE TITLE
[Bug] error when trying to enter the settings 

### ISSUE THREAD

**Issue by JohnnyWolf324** [BetterDiscord/BetterDiscord#1540] opened 2023-02-27 22:48 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When you install better and go to the settings of the application, an error about "unexpected failure" pops up. I did everything and reinstall then discord, then better, completely removed plugins and themes, even deleted all the root folders and did a clean installation - nothing, all the same

### Expected Behavior

open the settings and customize them to your needs

### Steps To Reproduce

1. i run in on windows 10 pro version 22H2
2. idk default one ig 
3. Trying to go to the application settings, a window appears that discord has found an unexpected error, and in the middle there is a reload button 
4. there is no error, only the text that "an unexpected error was found" 

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.0.9011

### Anything else?

![Снимок](https://user-images.githubusercontent.com/68712930/221703878-18d1aaca-2dda-4347-ab01-6578a224944e.PNG)

**Comment by lmoroz** [comment] 2023-02-27 22:50
Same problem

**Comment by SoulKnight05** [comment] 2023-02-27 22:53
Jep same here, ig its a common bug rn, some of my friends also have the exact same problem

**Comment by ItMeSarah** [comment] 2023-02-27 22:55
Known issue, a fix is being worked on.

**Comment by fr3nchalp4a** [comment] 2023-02-27 22:56
same on linux (fedora) here

**Comment by Aqua-GVPYT** [comment] 2023-02-27 22:59
Same issue, the old fix that fixed it last time doesnt work either.

**Comment by MegaShinySnivy** [comment] 2023-02-27 23:40
Can confirm, this happens regardless of any theme or plugins. The console outputs the following on crash...

`Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at wc (288aa17….js:1667)
    at d (288aa17….js:1602)
    at E (288aa17….js:1604)
    at e (288aa17….js:1606)
    at vs (288aa17….js:1618)
    at yu (288aa17….js:1663)
    at Oc (288aa17….js:1655)
    at Ic (288aa17….js:1655)
    at hc (288aa17….js:1654)
    at ic (288aa17….js:1651)
    at oc (288aa17….js:1650)
    at g (288aa17….js:1772)
    at L (288aa17….js:1773)
    at t.exports (ff334c0….js:21)
    at g.<computed> (ff334c0….js:36)
    at Number.m (ff334c0….js:36)
    at MessagePort.b (ff334c0….js:36)`

**Comment by Oreo030** [comment] 2023-02-27 23:59
I deleted everything, even localappdata, appdata from bdc and dc, still having the same issiue when i install bdc

**Comment by Knutsen** [comment] 2023-02-28 00:02
I have the same issue on my Mac M1.
OS: Ventura
I tried to install it via Discord canary and the regular discord, same issue.

**Comment by canerolu2019** [comment] 2023-02-28 00:06
Thank god im not the only one who has this issue right now. Others has it too. Oop

**Comment by rellcfw22** [comment] 2023-02-28 00:13
at this point im having an the issue where im trying to use betterdiscord with all the plugins i got but it wont even get to my messages lmao it just gives me the error lol

**Comment by Burntninjas** [comment] 2023-02-28 00:50
Experiencing same issue on fresh BD install.

**Comment by epicfacethe3rd** [comment] 2023-02-28 00:54
Issue confirmed on linux

**Comment by canerolu2019** [comment] 2023-02-28 01:26
Guys, any update so far??

**Comment by handylado** [comment] 2023-02-28 01:41
same issue with me :/

**Comment by epicfacethe3rd** [comment] 2023-02-28 01:54
> Guys, any update so far??

they're aware of the issue and are working on a fix @canerolu2019 , chill, they're just volunteers

**Comment by Baikele** [comment] 2023-02-28 03:37
Haven't fixed it yet? This problem seems to exist all the time. It happened when I was using it last year. I reloaded it a few times and it worked, but it didn’t work this time.

**Comment by iKatt** [comment] 2023-02-28 03:44
Just use Discord Canary or PTB until BD is patched.

**Comment by Baikele** [comment] 2023-02-28 03:46
> Just use Discord Canary or PTB until BD is patched.

Where can I download this?

**Comment by Baikele** [comment] 2023-02-28 03:53
Even using bd on Discord Canary also crashes

**Comment by Baikele** [comment] 2023-02-28 04:34
> ```
> @echo off
> cd %appdata%/betterdiscord/data
> taskkill /f /im discord.exe 
> curl  https://cdn.discordapp.com/attachments/826217269323235358/1079920833662816277/betterdiscord.asar -O
> ```
> 
> Make a bat file and Try to run this... i guess it will work... I got it from [Betterdiscord Discord server](https://betterdiscord.app/invite)

It's good, but I don't know why, the plugin can't be loaded normally

**Comment by airplaneboy14mc** [comment] 2023-02-28 04:57
> ```
> @echo off
> cd %appdata%/betterdiscord/data
> taskkill /f /im discord.exe 
> curl  https://cdn.discordapp.com/attachments/826217269323235358/1079920833662816277/betterdiscord.asar -O
> ```
> 
> Make a bat file and Try to run this... i guess it will work... I got it from [Betterdiscord Discord server](https://betterdiscord.app/invite)

is there a workaround for linux systems that you know of or might know someone that might know of it? or no?

**Comment by XxUnkn0wnxX** [comment] 2023-02-28 04:59
macos ver:
```
#!/bin/sh
echo "bd-repair"
cd ~/"Library/Application Support/betterDiscord/data"
killall Discord
curl -O "https://cdn.discordapp.com/attachments/826217269323235358/1079920833662816277/betterdiscord.asar"
```

**Comment by Baikele** [comment] 2023-02-28 05:02
![image](https://user-images.githubusercontent.com/70128689/221758699-06485d10-e4a2-4696-a0f9-c13ac6ffe9ae.png)

**Comment by jimmyli56** [comment] 2023-02-28 07:12
The latest update causes this issue, and in my testing affects all platforms. With plugins active, the client will not go past the loading animation. Removing plugins stored in the plugin folder does allow you to go past the loading screen, but it will still crash when entering settings. Currently uninstalling is the only fix.

**Comment by mirpton** [comment] 2023-02-28 09:17
This is so funny. Discord added Themes for Nitro Only and a week later This issue started.
It seems like Discord is trying to kill Better Discord and they are going to succeed unless Better Discord Devs do something about this issue.

**Comment by Baikele** [comment] 2023-02-28 09:30
If that's the case, that's too bad, bd's plugin system is great, but discord probably won't support it

**Comment by TheDingOfTheHud** [comment] 2023-02-28 10:48
dont know if this is also the case for everyone, but right clicking on a server name whilst in the server, also crashes discord. I would really like a fix for this

**Comment by Baikele** [comment] 2023-02-28 10:49
no

**Comment by moops44** [comment] 2023-02-28 10:54
the fix is here
https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

**Comment by Yatahu** [comment] 2023-02-28 11:06
There is the same error on Mac.

**Comment by embry0** [comment] 2023-02-28 11:14
> the fix is here https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

> ```
> @echo off
> cd %appdata%/betterdiscord/data
> taskkill /f /im discord.exe 
> curl  https://cdn.discordapp.com/attachments/826217269323235358/1079920833662816277/betterdiscord.asar -O
> ```
> 
> Make a bat file and Try to run this... i guess it will work... I got it from [Betterdiscord Discord server](https://betterdiscord.app/invite)

**Comment by embry0** [comment] 2023-02-28 11:16
> the fix is here https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

After trying this fix, I keep getting this problem with the BDFDB library plugin and every other plugin that uses this library

![image](https://user-images.githubusercontent.com/126282972/221838262-94e4ada6-2080-4a87-9d49-db23053f4cd5.png)

**Comment by embry0** [comment] 2023-02-28 11:19
> the fix is here https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

After trying this fix, I keep getting this problem with the BDFDB library plugin and every other plugin that uses this library

![image](https://user-images.githubusercontent.com/126282972/221839030-1386a933-6c0b-4893-9b6d-b0ca2a49bdd6.png)

**Comment by Yatahu** [comment] 2023-02-28 11:20
Yeah me too, I tried to reinstall this plugin, delete files and nothing works

**Comment by Risusama** [comment] 2023-02-28 11:41
> the fix is here https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

Can confirm this fixes original problem, which is the crash on opening Settings menu.

**Comment by steamhappy** [comment] 2023-02-28 11:54
> the fix is here https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

This fixed the original problem for me too but it crashes for me when I click on some servers which then puts Discord into a crashing loop unless I end it from the system tray.

**Comment by DabMK** [comment] 2023-02-28 12:48
I have the same issue on win 10

**Comment by southernpoint** [comment] 2023-02-28 13:18
I also have the same issue but on Arch Linux. At first, discord would crash at startup but after deleting everything it seems like only by opening the settings the crash will occur. I will try [this](https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389) to see if it'll fix my issue.

**Comment by EldraTheThird** [comment] 2023-02-28 13:50
me too bro ;-;

**Comment by p0s0** [comment] 2023-02-28 14:16
I have no clue if anyone else is having this issue, but recently I have been having messages either:

crash Discord whenever they're opened

or not load at all, even from a group chat until Discord is restarted (and even then the message may crash Discord)

**Comment by Infinitay** [comment] 2023-02-28 15:16
Can we rename this issue so that people stop creating new issues for the same bug?

**Comment by SnakeSixtysix** [comment] 2023-02-28 15:52
Just here to confirm this is universal I have this issue on macos ventura 13.0.1

**Comment by smt923** [comment] 2023-02-28 16:12
replacing the `.asar` does allow me to open my settings again but it seems like every actual plugin is broke, their settings pages no longer opens

**Comment by endersender365** [comment] 2023-02-28 17:11
> replacing the `.asar` does allow me to open my settings again but it seems like every actual plugin is broke, their settings pages no longer opens

Where do you replace the .asar file?

**Comment by endersender365** [comment] 2023-02-28 17:11
nvm i found it

**Comment by endersender365** [comment] 2023-02-28 17:15
Yeah, replacing the asar file doesn't work, and neither does removing the plugins and themes.

**Comment by canerolu2019** [comment] 2023-02-28 17:16
I tried that temporary fix yesterday and so far it works like a charm and i can apply the themes with no problem. The only downside is the plugins dont work sadly.

**Comment by 343GuiltySpark-04** [comment] 2023-02-28 17:18
> I also have the same issue but on Arch Linux. At first, discord would crash at startup but after deleting everything it seems like only by opening the settings the crash will occur. I will try [this](https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389) to see if it'll fix my issue.

did it work? im still having the issue on Debian

**Comment by JustDesoroxxx** [comment] 2023-02-28 17:51
Same issue here

**Comment by Zorunel** [comment] 2023-02-28 17:54
> > replacing the `.asar` does allow me to open my settings again but it seems like every actual plugin is broke, their settings pages no longer opens
> 
> Where do you replace the .asar file?

replace in %appdata%\BetterDiscord\data

**Comment by Hitazaki** [comment] 2023-02-28 19:28
> replacing the .asar does allow me to open my settings again but it seems like every actual plugin is broke, their settings pages no longer opens

it doesn't really seem to work for me cause I still get crashes in the settings :/

**Comment by M-archand** [comment] 2023-02-28 20:47
> the fix is here https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389

Can confirm this works for me on W10, can go into settings now without crashing. Plugins are still broken but at least theme still works.

**Comment by lukiiimohh** [comment] 2023-03-01 00:42
Not working properly on W11 with the installed `.asar` but working (yes, just working) with the `.asar` from the workaround. For example is someone is playing a game with the overlay ON it crashes if you click on the profile. Can't right click any server o person profile and some plugins are so buggy. Cheers!

**Comment by HuTao69** [comment] 2023-03-01 01:04
The `.asar` from the workaround seems to work on macOS Ventura 13.2.1. Plugins are absolutely broken though - but themes work.

**Comment by aqtsalt** [comment] 2023-03-01 15:31
same

**Comment by Pbg4444** [comment] 2023-03-01 18:40
same

**Comment by rauenzi** [comment] 2023-03-01 21:51
This has been fixed in the latest release

**Closed by rauenzi** 2023-03-01 21:51 UTC
Labels: bug
