### ISSUE TITLE
[Bug] BD crashes when switching accounts using experiment: account switcher

### ISSUE THREAD

**Issue by kateisprettydamngreat** [BetterDiscord/BetterDiscord#1114] opened 2021-11-11 04:16 UTC
When switching accounts, the BD app will periodically crash

**To Reproduce**
Open the experiments menu, enable account switcher, add a second account, and switch back and forth

**Expected Behavior**
It switches smoothly without crashes

**Discord Version**

**Comment by doggybootsy** [comment] 2021-11-11 04:17
Does this happen without bd, if so it's not a bd issue

**Comment by kateisprettydamngreat** [comment] 2021-11-11 04:21
No, it has no adverse affect when switching except bd gives the error that it disabled itself

**Comment by SmolAlli** [comment] 2021-11-11 04:58
I remember somewhat recently this being a plugin issue.
Can you please check:
That this is definitely a BetterDiscord issue (via[this guide](https://smolalli.github.io/BetterDiscord/vanilla-commands.html) )
If the console produces any errors on the crash screen (ctrl/cmd shift i, any red errors that pop up in the console)
Btw [join the Discord server](https://betterdiscord.app/invite) and we can help you out more easily. It'd be preferable if you mentioned your problems and sent screenshots of the error there, then report back to here when we're sure that it's a BetterDiscord issue itself and not a plugin.

**Comment by dav1312** [comment] 2021-11-11 05:59
Duplicate of #1096

**Comment by Inve1951** [comment] 2021-11-11 14:39
"Experiments" are experimental discord features. BD will never add special support for them. If they don't work, they don't work.

**Closed by Inve1951** 2021-11-11 14:39 UTC
Labels: bug

**Comment by kateisprettydamngreat** [comment] 2021-11-12 06:51
Nope, it's pushed to beta, just limited roll out right now.

**Comment by Inve1951** [comment] 2021-11-12 21:41
#1096 is the tracking issue for this bug
