### ISSUE TITLE
[Bug] Super Reactions keep crashing BD

### ISSUE THREAD

**Issue by BloodWorkVR** [BetterDiscord/BetterDiscord#1602] opened 2023-04-08 15:55 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

when hovering over a Super Reaction Discord will freeze and mostly crash, sometimes it recovers after couple minutes

### Expected Behavior

Discord not Crashing/Freezing

### Steps To Reproduce

Open BetterDiscord
Hover on any Super Reaction

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.2

**Comment by ItMeSarah** [comment] 2023-04-09 01:34
Unable to reproduce, are you sure it's not caused by a plugin? Move all of your plugins out of the plugin folder and test again, and if it still happens then test with BD uninstalled

**Comment by billygachi** [comment] 2023-04-09 22:49
Ive managed to reproduce it.
1. Open a kernel driver protected game such as Valorant
2. Have discord open with game overlay toggled on. Wait until discord recognises the game
3. Hover over a superreact and discord with bd installed and it will max out the load of its cpu thread, freezing it
It doesnt happen on vanilla discord and disabling game overlay fixes the issue

**Comment by BloodWorkVR** [comment] 2023-04-10 01:39
Thanks i disabled the overlay and will try it soon again.

**Comment by Rushaway** [comment] 2023-04-18 06:18
As @billygachi said. It's the overlay who generate the crash.
I still have this issue when overlay is enabled.

**Comment by neonmaus** [comment] 2023-04-22 10:59
> Ive managed to reproduce it.
> 
> 1. Open a kernel driver protected game such as Valorant
> 2. Have discord open with game overlay toggled on. Wait until discord recognises the game
> 3. Hover over a superreact and discord with bd installed and it will max out the load of its cpu thread, freezing it
>    It doesnt happen on vanilla discord and disabling game overlay fixes the issue

I can also reproduce the error this way

**Comment by MythiixLtd** [comment] 2023-06-25 18:43
any update to this anytime soon please

**Comment by MythiixLtd** [comment] 2023-07-15 13:35
i once again ask for a update

**Comment by MythiixLtd** [comment] 2023-07-15 13:59
.reaction-3vwAF2[style*="background"] {
    display: none;
}

put this in custom css it hides them until they actually manage to fix anything

**Comment by rauenzi** [comment] 2023-08-29 03:55
I cannot reproduce this issue so I have no idea how to fix it.

**Comment by rauenzi** [comment] 2024-02-22 05:10
Based on [this comment](https://github.com/BetterDiscord/BetterDiscord/issues/1602#issuecomment-1501229999) it's locking up Discord just like #1463 so I'm closing this in favor of that one.

Unfortunately I've no idea how to fix either one as I've never reproduced it and also BetterDiscord specifically does not inject into the overlay intentionally.

**Closed by rauenzi** 2024-02-22 05:10 UTC
Labels: bug, needs info, can't reproduce
