### ISSUE TITLE
[Custom CSS]

### ISSUE THREAD

**Issue by Dillian0** [BetterDiscord/BetterDiscord#955] opened 2021-07-26 00:33 UTC
**Describe the Bug**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by Overimagine1** [comment] 2021-07-26 00:36
So where’s the bug report?

**Comment by Zachdogg1** [comment] 2021-07-26 17:50
I have a problem I believe Dillian is trying to talk about. The custom css tab does nothing when clicked on. My existing custom css is still running just fine, but I cannot access or edit the custom css, the entire editor does not work at all, but only on the css tab. The editor still works on the plugin and themes settings tabs. Maybe his error is completely different but he did not really put any info

**Comment by dav1312** [comment] 2021-07-26 22:50
> I have a problem I believe Dillian is trying to talk about. The custom css tab does nothing when clicked on. My existing custom css is still running just fine, but I cannot access or edit the custom css, the entire editor does not work at all, but only on the css tab. The editor still works on the plugin and themes settings tabs. Maybe his error is completely different but he did not really put any info

This issue was already closed ( #949 ) because it was alrady fixed in 87efffb

**Comment by Technetium1** [comment] 2021-07-27 03:12
I can confirm that the fix referenced in issue 949 works.

**Closed** 2021-07-27 17:20 UTC
Labels: bug
