### ISSUE TITLE
[Bug] Channel list has to be clicked twice to select a server after startup of discord

### ISSUE THREAD

**Issue by binarynoise** [BetterDiscord/BetterDiscord#1277] opened 2022-04-14 18:08 UTC
**Describe the Bug**

I have to click twice in the server list to select a server the first time after discord started. 
In the inspector I saw that after the first click, the whole <nav> is replaced. Even if I wait some time before I use it first.

**To Reproduce**

- Create a fresh installation of discord on a Linux based machine (reproduced on Reborn OS/Arch and Linux Mint, you can use a live ISO in a vm).
- Install BetterDiscord.
- Log in.
- Select a server in the navbar on the left, select server again to actually get there.  
  Happens again if restarting Discord.

**Expected Behavior**

You are directly taken to the server.

**Screenshots**

 \-

**Discord Version**

Stable and Canary

**Additional Context**

 \-

**Comment by SmolAlli** [comment] 2022-04-14 23:18
Duplicate of #1203

**Closed** 2022-04-23 04:30 UTC
Labels: bug
