### ISSUE TITLE
[Bug] Installer empty Window

### ISSUE THREAD

**Issue by ChickChuck2** [BetterDiscord/BetterDiscord#1547] opened 2023-02-28 17:14 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I was install the BD 1.8.4 and after open return an empty screen
![Screenshot_3](https://user-images.githubusercontent.com/48648882/221927458-5ee6c60b-6dd9-4291-800f-5123ebb38f76.png)

### Expected Behavior

Open the BD installer and select one of options 
Install, repair, exit
but taht's window was CLEAN

### Steps To Reproduce

1° Open the BD installer v1.8.4
DONE! I get an empty screen

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.8.4

**Comment by rauenzi** [comment] 2023-03-01 21:56
Duplicate of https://github.com/BetterDiscord/Installer/issues/310

**Closed by rauenzi** 2023-03-01 21:56 UTC
Labels: bug
