### ISSUE TITLE
[Feature] fast recover

### ISSUE THREAD

**Issue by speedlorenzo12** [BetterDiscord/BetterDiscord#1658] opened 2023-08-18 08:17 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

an innovative feature for betterdiscord that will ensure that the client is not cashed completely but recover immediately but with an error message

I don't know if it's really possible but I'll try

### Anything else?

vencord crashes but doesn't crash at all

**Comment by rauenzi** [comment] 2023-08-18 09:36
This is part of better crash recovery and prevention. duplicate of #1018

**Closed by rauenzi** 2023-08-18 09:36 UTC
Labels: enhancement
