### ISSUE TITLE
[Feature] Frameless option

### ISSUE THREAD

**Issue by DaBluLite** [BetterDiscord/BetterDiscord#1426] opened 2022-10-02 13:30 UTC
**Is your feature request related to a problem? Please describe.**
My feature request is related to the lack of a frameless mode for the linux discord app

**Describe the feature you'd like**
Enable/uncomment the 2 lines that enable the frame settings in BD's `settings.json` file

**Additional context**
It would just be nice to just disable he frame of the discord app and use our own in one way or another

**Comment by DaBluLite** [comment] 2022-10-04 17:24
[This commit](https://github.com/DaBluLite/BetterDiscordFrameless/commit/e9bc4eb44aa7187c38e3cbaf5cb3703d29998425) is the frameless option being uncommented (in [DaBluLite/BetterDiscordFrameless](https://github.com/DaBluLite/BetterDiscordFrameless))

**Comment by rauenzi** [comment] 2023-03-04 05:34
Duplicate of #1062

**Closed by rauenzi** 2023-03-04 05:34 UTC
Labels: enhancement
