### ISSUE TITLE
Custom CSS Menu not loading in at all[Bug]

### ISSUE THREAD

**Issue by Dorfde** [BetterDiscord/BetterDiscord#956] opened 2021-07-26 11:47 UTC
So recently  I downloaded BetterDiscord since I found this one theme I thought was pretty cool. However the way how you would set it up is by pasting the code it self in the Custom CSS menu. So I open the options menu, scroll down to the BetterDiscord section, click on Custom CSS and it doesn't load in. Like, at all. All the other menus load in, but this doesn't! I even tried installing other themes, they work just fine but they still don't let me boot up the Custom CSS menu!
The version of discord I'm using is stable, if it means anything I'm using a laptop running windows 7 ultimate.

**Comment by QbDesu** [comment] 2021-07-26 11:49
Duplicate of #949
Same instructions as in there.

**Closed** 2021-07-26 14:17 UTC
Labels: bug
