### ISSUE TITLE
[Bug] BetterDiscord crashes when I try to click on the emoji icon beside the message bar.

### ISSUE THREAD

**Issue by chanhh01** [BetterDiscord/BetterDiscord#1125] opened 2021-11-13 07:37 UTC
Whenever I tried to click on the emoji icon beside the message bar, my BetterDiscord would crash and show "You Died" page.

Just yesterday, my BetterDiscord was working fine and i was able to choose emojis from emoji tab normally without having it to crash like it does just now.

![image_2021-11-13_153250](https://user-images.githubusercontent.com/84566394/141610259-24f31828-0ece-4f04-aa6e-f295198ab0bc.png)
![image_2021-11-13_153306](https://user-images.githubusercontent.com/84566394/141610271-435a2754-d4f5-438a-92f9-9bfe5be7c0f3.png)

**Discord Version**
Stable 104752 (000c742)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.19041)

**Additional Context**
The error page tried to relate the error to my plugins but none of them were the cause of it since the error still occurred even after removing the plugins.

**Comment by SmolAlli** [comment] 2021-11-13 07:37
Duplicate of #1116

**Comment by doggybootsy** [comment] 2021-11-13 07:38
duplicate of like the last 5 issues and https://github.com/BetterDiscord/BetterDiscord/issues/1116

**Closed** 2021-11-13 09:11 UTC
Labels: bug
