### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by gaoningguo** [BetterDiscord/BetterDiscord#1725] opened 2024-03-15 07:53 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

Automatically update or remind to update when there is a new version. Every time you open Discord and find that the theme and plugin you set are invalid, you will investigate whether it is caused by the update

**Comment by Riddim-GLiTCH** [comment] 2024-03-15 10:11
The fact that BD is gone should already be your reminder to reinstall BD.
Automatic reinstallation is not viable due to the current method of injection used.
The team would have to rewrite the injector and loader for something like this to be viable in the first place which is not easily done.

**Comment by BialySztorm** [comment] 2024-05-13 18:38
What about using [Zwylair code](https://github.com/Zwylair/BetterDiscordAutoInstaller), to make option for auto update on startup, i mean, add checkbox for it, and it will add the autoinjector on startup (modify it a little, so it gonna check current installed and current version of BD and inject only on new version?

**Comment by Riddim-GLiTCH** [comment] 2024-05-23 09:16
> @BialySztorm Commented:
> What about using [Zwylair code](https://github.com/Zwylair/BetterDiscordAutoInstaller), to make option for auto update on startup, i mean, add checkbox for it, and it will add the autoinjector on startup ?


This code is unverified and not supported by BetterDiscord. While it may serve the purpose needed I do not reccomend its use. Use it at your own risk

**Comment by zerebos** [comment] 2024-08-30 00:22
Duplicate of #1231

**Closed by zerebos** 2024-08-30 00:22 UTC
Labels: enhancement
