### ISSUE TITLE
[Bug] Installing plugin update on betterdiscord version 1.2.0

### ISSUE THREAD

**Issue by thegame4craft** [BetterDiscord/BetterDiscord#894] opened 2021-07-10 09:43 UTC
**Describe the Bug**
I have a plugin update for ZeresPluginLibaray and i will to install it. if i click on the name betterdiscord crashes and normal discord (without injection) starts. 

**To Reproduce**
Open betterdiscord and install the latest update (1.2.0) and installing a update.

**Expected Behavior**
Betterdiscord will install normally the update and not crashes

**Screenshots**
![grafik](https://user-images.githubusercontent.com/48205247/125158854-f2725580-e173-11eb-9501-e6d686b44aee.png)

**Discord Version**
Stable 89709 (8d00f68)
BetterDiscord 1.2.0
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

**Additional Context**

**Comment by dav1312** [comment] 2021-07-10 09:44
Duplicate of #888

**Closed** 2021-07-10 13:17 UTC
Labels: bug
