### ISSUE TITLE
Theme Editor does not work.[Bug]

### ISSUE THREAD

**Issue by CloudX713** [BetterDiscord/BetterDiscord#886] opened 2021-07-09 17:03 UTC
**Describe the Bug**
After opening the Editor for a Theme, a blank box appear (like standard) with NO text. You cant make it fullscreen and you cant close this window (use STRG+R or restart Discord.

**To Reproduce**
Open settings
Go to Themes
Click the Edit symbole
Blank box appears.

**Expected Behavior**
The Editor should open normally with the CSS Text of the Theme.

**Screenshots**
![Screenshot 2021-07-09 190247](https://user-images.githubusercontent.com/72802595/125113015-4fc0c500-e0e8-11eb-905b-bc1cd1fc9f39.png)

**Discord Version**
Stable 89550 (3c2108a)
BetterDiscord 1.2.0
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

**Additional Context**
For further Information, please ask.

**Comment by dav1312** [comment] 2021-07-09 17:05
Duplicate of #864

**Closed** 2021-07-09 17:38 UTC
Labels: bug
