### ISSUE TITLE
[Bug]I am not able to accept the license agreement of better discord on MacOS Big Sur Version 11.4

### ISSUE THREAD

**Issue by Fe4rXI** [BetterDiscord/BetterDiscord#947] opened 2021-07-21 14:54 UTC
**Describe the Bug**
When I click on it shows that it is clicking on it but it is not getting the blue tick in the box.

**Expected Behavior**
A blue tick should appear when I accept the agreement

**Screenshots**

https://user-images.githubusercontent.com/87511632/126509322-507559b1-f01d-4354-88e3-00faedc40676.mov

**Discord Version**

Stable and Canary both
**Additional Context**

**Comment by fowlis** [comment] 2021-07-21 14:55
This is very well known, click the text next to the box and it will work.
Should be fixed in the next installer update

**Comment by dav1312** [comment] 2021-07-21 14:55
Thats an issue with the installer, not with Betterdiscord
https://github.com/BetterDiscord/Installer/issues/177

**Comment by Fe4rXI** [comment] 2021-07-21 14:57
> This is very well known, click the text next to the box and it will work.
> Should be fixed in the next installer update

Tysm dude it worked :D

**Comment by Overimagine1** [comment] 2021-07-21 19:17
Please close this issue as the problem is solved.

**Closed** 2021-07-27 17:20 UTC
Labels: bug
