### ISSUE TITLE
[Feature] Discord Development Support

### ISSUE THREAD

**Issue by iAutistic** [BetterDiscord/BetterDiscord#1534] opened 2023-02-19 20:39 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I use Discord Development, Could you guys add Discord Development to the installation list.

![image](https://user-images.githubusercontent.com/68719131/219973937-7f50fcb7-77ab-4e73-93ce-5f2e991a0190.png)
![image](https://user-images.githubusercontent.com/68719131/219973923-35dc63cb-8b62-4752-a28a-c45a4b856eab.png)

**Comment by maenDisease** [comment] 2023-02-19 21:10
Duplicate of https://github.com/BetterDiscord/BetterDiscord/issues/520

**Closed** 2023-02-19 22:01 UTC
Labels: enhancement
