### ISSUE TITLE
[Bug] Users License Agreement Error

### ISSUE THREAD

**Issue by RadioDemon23** [BetterDiscord/BetterDiscord#1036] opened 2021-09-15 20:12 UTC
I wanted to get Better Discord again because I thought it was cool. Downloaded it and opened it no problem, but I got to the users license agreement page and when I would click 'I agree blah blah blah', it wouldn't register as me clicking it.

I've reinstalled BD about 3 times now, and none of my attempts have worked. It all ends up doing the same thing.

![image](https://user-images.githubusercontent.com/90799293/133502408-89994da7-e844-493c-b98f-4daed7b91b50.png)

All I did was install and open it- Read through it, maybe it had a time limit, gave it about 10 minutes, still wouldn't do anything.

I don't know if it's just because I'm stupid or missing something orrrr....

**Comment by RadioDemon23** [comment] 2021-09-15 20:14
im immensely stupid and now it's working but i don't know why

**Comment by fowlis** [comment] 2021-09-15 20:14
This is very well known, click the text next to the box and it will work.
Should be fixed in the next installer update.

Duplicate of #947

**Closed** 2021-09-15 20:13 UTC
Labels: bug
