### ISSUE TITLE
[Feature]Edit app.asar in a way such that BetterDiscord is installed with every Discord update!

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [BetterDiscord/BetterDiscord#1729] opened 2024-03-19 20:14 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

And also have the ability to rollback Discord updates and stop forced updates!

### Anything else?

I think app.asar has the updator logic but it may also be in the Discord executable so we may need Ghidra for that.

**Comment by H-A-M-G-E-R** [comment] 2024-03-19 20:16
and why there are always 13 updates instead of a random number

**Comment by H-A-M-G-E-R** [comment] 2024-03-19 20:19
but when i edit app.asar discord refuses to start how to fix that

**Comment by Riddim-GLiTCH** [comment] 2024-03-19 20:23
You can bypass any host updates by adding the following rule to `discord/settings.json`
```json
{
    "SKIP_HOST_UPDATE": true
}
```
An example of which can be seen in this screenshot.
![image](https://github.com/BetterDiscord/BetterDiscord/assets/87764384/e93aac79-962e-4e3e-b1c1-917e4b906529)

I do not believe this will resolve the issue of Discord patching out BetterDiscord on host updates, as occasionally, the `app.asar` file in question also gets overwritten by Discord host updates.

Additionally, I can highly reccomend [OpenAsar](https://openasar.dev) which allows you to skip update checks on starup, which should also allow you to bypass host updates.

Currently, I am aware of the BetterDiscord installer package being [rewritten in wails](https://github.com/BetterDiscord/Installer/tree/wails) in the hopes of adding more control of BetterDiscord injection being a bit more permanent. 


I hope these workarounds are helpful to you until a solution is found.

**Comment by bluedoomcapZZang** [comment] 2024-04-06 18:47
저건 남에게나 도둑넘이지..

**Comment by PaperVb64** [comment] 2024-05-13 20:14
> I do not believe this will resolve the issue of Discord patching out BetterDiscord on host updates, as occasionally, the `app.asar` file in question also gets overwritten by Discord host updates.

Couldn't you just bundle a file that checks if the discord app is updated, than patches the asar?

**Comment by Riddim-GLiTCH** [comment] 2024-05-15 05:46
> > I do not believe this will resolve the issue of Discord patching out BetterDiscord on host updates, as occasionally, the `app.asar` file in question also gets overwritten by Discord host updates.
> 
> Couldn't you just bundle a file that checks if the discord app is updated, than patches the asar?

Technically yes, but you would have to have a subprocess that checks when Discord's Sr has changed to then kill it, then reinstall better Discord and then start Discord again. Due to better Discord needing an entire app restart in order to load correctly, this experience will be janky to the user to say the least. And I do believe that a lot of users will complain that their Discord is not starting correctly or starting very weirdly if this is to be implemented. Worse yet, I do believe some might complain that their Discord might be infected with malware seeing as how better Discord already has a bit of a tarnished reputation for some infected binaries being spread on the internet and people not checking where they got their binaries from, but just blaming the name of the app. 


Either way, I think the manager that is upcoming is a better idea than just having a thing that kills Discord after it's already started. Then restart Discord with BD injected as if nothing happened.

**Comment by zerebos** [comment] 2024-08-30 00:23
Duplicate of #1231

**Closed by zerebos** 2024-08-30 00:23 UTC
Labels: enhancement
