### ISSUE TITLE
[Bug] BD Lagging Discord Badly

### ISSUE THREAD

**Issue by Sundewplays** [BetterDiscord/BetterDiscord#1702] opened 2023-12-15 01:30 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

**_With BD I can't do the following:_**
_Use / commands
Change Discord Themes
Favorite/Unfavorite GIFs
Move or join servers without Discord freezing
Can't enter emoji picker or type ":(emoji name):"
Can't change status
Can't toggle most stuff_
All of this is happening without plug-ins or themes and tons of people are having the same issue. This _should_ be reproducable.

### Expected Behavior

It shouldn't freeze or crash when I do these things.

### Steps To Reproduce

Just try doing anything that I listed in the "Describe the Bug" Section

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.5 and v1.9.6

### Anything else?

There is also a support thread for this in the BetterDiscord server.

**Comment by rauenzi** [comment] 2023-12-15 01:43
> This should be reproducable.

Definitely cannot reproduce this even a little. This sounds like something has gone very wrong with your installation, please remove BD, reinstall Discord, launch it, then install BD.

**Comment by Sundewplays** [comment] 2023-12-15 01:44
mkay then ill ask the other 20 ppl to do that

**Comment by Sundewplays** [comment] 2023-12-15 01:45
wait I cant uninstall discord

**Comment by Sundewplays** [comment] 2023-12-15 01:45
also this mostly got fixed for me but others are still saying they have issues

**Comment by Riddim-GLiTCH** [comment] 2023-12-15 02:10
Unable to reproduce this on my machines either. This includes the potato I use for work.

**Comment by rauenzi** [comment] 2023-12-15 04:04
I've found one potential optimization that can help users with slow/overused filesystems. I am having some people with lag related issues test this.

**Comment by abandon-the-flesh** [comment] 2023-12-15 05:30
Yes, easily reproduced. Please leave discord running for over 3-4 hours. I'm not uninstalling and reinstalling for the 10th time.
 
https://discord.com/channels/86004744966914048/1168801530313453630/1173117072646098975

https://cdn.discordapp.com/attachments/1168801530313453630/1173117071341649960/2023-11-11_22-27-13.mp4?ex=6587b369&is=65753e69&hm=fcf3e031627586f31242eec9f5bf0122550646487f3a518e2e8bf59c03af2421&

**Comment by rauenzi** [comment] 2023-12-15 05:34
> Yes, easily reproduced.

For you perhaps, but I've never encountered this.

> Please leave discord running for over 3-4 hours.

I leave it open all day.

> I'm not uninstalling and reinstalling for the 10th time.

This was not directed towards you.

**Comment by rauenzi** [comment] 2023-12-15 05:36
If anyone experiencing this issue would like to test a potential fix, locate your BetterDiscord folder and the file `betterdiscord.asar`. Delete it (or rename it) and replace it with [this version](https://cdn.discordapp.com/attachments/341062370627682315/1185092720717471754/betterdiscord.asar?ex=658e5a9a&is=657be59a&hm=a46c88f9070f5e5a9ffbd3dafffb0a2b29635988ec0f421a97b0fa618be042e2&). Then fully close your Discord client and start it again for it to take effect.

**Comment by 2l47** [comment] 2023-12-15 17:25
@rauenzi The updated asar file seems to immediately and completely resolve the issues for me. Thanks for looking into this! Out of curiosity, what did you change?

**Comment by abandon-the-flesh** [comment] 2023-12-18 20:40
It's been 48+ hours with Discord open since replacing the asar file. The freezing and crashing from changing status, favoriting a gif, or opening the emote menu no longer occurs. The only lag I am still experiencing to a small degree is opening the emoji menus, where there is still "pop in" when servers emoji list is collapse. My solution was just to leave them all open so they remained loaded. 

Hopping channels or servers causes the same small "pop in" and a bit more lag/wait time. Not sure if this is related. 
I'm glad the program is at least usable now. Thanks for your support and the fix.

**Comment by rauenzi** [comment] 2023-12-18 21:01
Can you elaborate on this "pop in" or provide video? I don't really experience any delay in opening the emoji menu or when switching servers. Do you have any plugins enabled?

**Comment by abandon-the-flesh** [comment] 2023-12-18 21:17
I have the following plugins enabled:
BDFDB
ChatAliases
LastFMRichPresence
RemovedBlockedUsers
RemoveChatButtons
SpellCheck
Translator
ZeresPluginLibrary

I don't use any themes. I do have some custom CSS.

There's no delay opening the menu itself, but the collapsed groups of emoji - and it's not a bother if you leave them all open. If you do toggle to collapse the groups they just take a second to load back in. Not a huge deal. 

[https://cdn.discordapp.com/attachments/1123471080921772052/1186415951856541786/2023-12-18_15-06-52_-_Trim.mp4](url)

**Comment by rauenzi** [comment] 2023-12-18 21:51
The delay you are showing there in that video is comparable to how Discord looks for me without any client mods. Have you tried comparing this to when you have no client mods?

**Comment by abandon-the-flesh** [comment] 2023-12-18 22:16
Nope. Glad it's not related. Thanks for checking into it.

**Comment by rauenzi** [comment] 2023-12-18 23:39
This change was released in 1.9.7

**Closed by rauenzi** 2023-12-18 23:39 UTC
Labels: bug

**Comment by Sundewplays** [comment] 2023-12-19 08:55
thank you so much!
