### ISSUE TITLE
[Bug] I need to double click on a server to open after first startup

### ISSUE THREAD

**Issue by AndRo-Marian** [BetterDiscord/BetterDiscord#1203] opened 2022-02-07 15:42 UTC
**Describe the Bug**
When I open discord and clicking on a server to open it. I does nothing. I need to click again.

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**
Stable 113584 (3f697f2)
BetterDiscord 1.5.1
Host 1.0.9003 Windows 10 64-Bit (10.0.17763)

**Comment by WatanabeDaiki135** [comment] 2022-02-08 07:33
Same with me, but mine it's scrolled down a bit so I have to scroll it back up then re-click the server icon again smh

**Comment by howdoiusekeyboard** [comment] 2022-02-09 08:55
Yeah same with me, when I first click a server after I launch the app, it shakes the server list. So I have to click twice to enter a server.

**Comment by cmd430** [comment] 2022-02-16 02:55
This bug also seems to affect opening DMs after first launch

**Comment by SmolAlli** [comment] 2022-02-18 00:11
This occurs without any plugins installed into BetterDiscord, and does not occur on Vanilla discord.

**Comment by usrDottik** [comment] 2022-02-19 04:11
yeah, I have the same issue

**Comment by LillieSatou** [comment] 2022-04-22 17:27
Can reproduce with a base BD install as of the latest Discord Stable update. Uninstalling BD fixes the issue. CTRL-Tab & Shift-Ctrl-Tab (Default Discord keybinds for changing servers) are workarounds for the time being.
(Stable 124979 (80e9bf7) Host 1.0.9004)

**Comment by binarynoise** [comment] 2022-04-23 10:15
I also have this bug.

In the inspector I saw that after the first click, the whole `<nav>` is replaced. Even if I wait some time before I use it first.

## To Reproduce

- Create a fresh installation of discord on a Linux based machine (reproduced on Reborn OS/Arch and Linux Mint, you can use a live ISO in a vm).
- Install Discord and BetterDiscord.
- Log in.
- Select a server in the navbar on the left, select server again to actually get there.
- Happens again if restarting Discord.

**Comment by QbDesu** [comment] 2022-04-24 16:21
This is related to the way the BetterDiscord's theme helper classes are currently applied to the server list. We are aware of this bugs an there is already an experimental fix around that has the potential to break very quickly though.

Please refrain from telling us that you are experiencing it too because everybody is. Every Discord variant and every platform is affected. For now just sit tight please and wait for it to be fixed.

**Comment by rauenzi** [comment] 2022-10-12 19:49
This is fixed with the latest update

**Closed by rauenzi** 2022-10-12 19:49 UTC
Labels: bug

**Comment by binarynoise** [comment] 2022-10-16 01:15
@rauenzi 
Doesn't look like that. That still is an issue for me.

**Comment by JourneyOver** [comment] 2022-10-18 10:26
Issue seemed to have been fixed as I experienced a day or two of this not happening on first start/refresh of discord, but it does seem to be back again :/

**Comment by binarynoise** [comment] 2022-12-11 19:13
@rauenzi 
Would you please open this issue again?
It did not go away.
