### ISSUE TITLE
[Bug] Update plugins on top bar crashes BD

### ISSUE THREAD

**Issue by Jackaroo05** [BetterDiscord/BetterDiscord#902] opened 2021-07-14 14:28 UTC
**Describe the Bug**
When you go to update plugins on the blue top bar BD crashes and restarts regularly without BD.

**To Reproduce**
1. Have a plugin that needs updating
2. Click plugin name at the top blue bar
3. BD crashes and Discord starts normally

**Expected Behavior**
Plugins should be updated without a crash.

**Screenshots**
Attached Video

**Discord Version**
Stable

**Additional Context**
None

https://user-images.githubusercontent.com/22356378/125639430-29f1455c-b4c7-4228-ab81-71cd39037b17.mp4

**Comment by fowlis** [comment] 2021-07-14 14:30
Update ZeresPluginLibrary manually, use this link:
https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
Use CTRL + S to save the page as a .plugin.js and place it into the plugins folder.
Hope this helps!

**Comment by dav1312** [comment] 2021-07-14 14:51
Duplicate of #888

**Comment by rauenzi** [comment] 2021-07-14 15:06
See above. Reinstalling BD once more also repairs it.

**Closed by rauenzi** 2021-07-14 15:06 UTC
Labels: bug
