### ISSUE TITLE
High CPU usage with BD Discord  [Bug]

### ISSUE THREAD

**Issue by BlueStarBRS** [BetterDiscord/BetterDiscord#1308] opened 2022-05-20 17:39 UTC
**Describe the Bug**
i have noticed that my discord is going from normaly 2-4% cpu ussage 
but with installed BD discord its going to 20-50% Usage + the desktop manager or dwm usage is going up too i regoniced this on my both PC´s!

**To Reproduce**
idk use bd discord 

**Expected Behavior**
just a little higher usage and not overusing my CPU 

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/169581655-c0e46ad5-566f-4a46-9929-9cf88fe0b0c3.png)
![image](https://user-images.githubusercontent.com/25110093/169581732-59dcf6d8-0a7d-4de5-8ebb-8bcc6cfe3dca.png)
8-12% (not normal)

**Discord Version**
![image](https://user-images.githubusercontent.com/25110093/169581833-49c81b2d-f262-4142-834a-eb531a4df9c8.png)

**Additional Context**
My Systems:

System 1:
CPU: Ryzen 5 1600 Stock 3.2ghz
GPU: GTX 970 MSI
RAM: 16gb 2933mhz  cl 16
BOARD: Asus Prime 370x
OS: Windows 10 Pro
SSD 960 256GB
3TB Harddisk Toschiba p300

System 2:
CPU: Ryzen 5 2600 with OC 4.02ghz
GPU: GTX 980 TI SC EVGA
RAM: 16gb 2933mhz  cl 16
BOARD: B450 Aorus Elite
OS: Windows 10 Pro
SSDs 960 256GB,2x MX500 1TB

**Comment by hauntingly** [comment] 2022-05-21 20:35
Having the same issue as well.

**Comment by ItMeSarah** [comment] 2022-05-22 00:22
This is generally caused by your theme being too intensive with animations, transitions, etc. A few things can help with this, the first is use a different theme that doesn't have a ton of animations or transitions. Another thing is enable reduced motion in Discord Settings > Accessibility, and disable Hardware Acceleration in  Discord settings > Advanced if your GPU usage is also high.

**Comment by BlueStarBRS** [comment] 2022-05-22 15:11
the problem is i alreaddy tried all these steps and it dosnt help the resson why i postet it here

**Comment by Saltssaumure** [comment] 2022-05-24 04:32
Does this still occur if you remove all themes and plugins?

**Comment by christianbrasch** [comment] 2022-05-26 02:14
Having the same problem as well

**Comment by BlueStarBRS** [comment] 2022-06-11 18:40
> Does this still occur if you remove all themes and plugins?

yep with plugins is a little bit more

**Comment by BlueStarBRS** [comment] 2022-06-11 18:40
> Having the same problem as well

i feel you bro

**Comment by rauenzi** [comment] 2022-06-24 21:50
I cannot reproduce this with no plugins or themes. Currently using 0.1%

**Comment by BlueStarBRS** [comment] 2022-06-24 23:55
> I cannot reproduce this with no plugins or themes. Currently using 0.1%

both systems are AMD Ryzen 

if you need some logfiles or details etc. tell me i will send.

**Comment by Saltssaumure** [comment] 2022-06-25 02:34
On my computer, which is running a Ryzen 2600X/3600 (recent upgrade) + 1060 6GB, I don't have this issue. Just for the record to show that Ryzen processor is not the issue.
![image](https://user-images.githubusercontent.com/29710355/175754906-7851f45f-5d1e-4b32-b82a-d55bc8f6ab1f.png)

**Comment by rauenzi** [comment] 2022-08-31 15:15
I tried on my Ryzen build as well as my intel-based laptop and could not reproduce the issue on either.

**Comment by rauenzi** [comment] 2022-10-12 19:46
Many crashing, memory, and cpu issues have been fixed with the latest update.

**Closed by rauenzi** 2022-10-12 19:46 UTC
Labels: bug, can't reproduce
