### ISSUE TITLE
[Feature] Tutorial on plugin-making

### ISSUE THREAD

**Issue by MajorBarnulf** [BetterDiscord/BetterDiscord#405] opened 2020-07-29 22:52 UTC
## feature
online documentation on how to make plugins
(eventually also for themes, but this subject is probably easier to understand).

## context
Hi, so I am a "kinda self-proclaimed" dev, I do a bit of js on my free time, I made web app with node.js for personal projects and electron apps to make my life easier, but now I want to make discord plugins, the thing is;
I am not very experienced in this field and I lack ressources, could it be possible to have documentations on how to make them/basic tutorial(s) to do simple things?

I am also certain that this kind of docs could make more people use better discord / make more devs develop plugins, and therefore be a good thing for betterDiscord in general.

### P.S.
if you know of any resources that might help me making a plugin, could you share them? even if it's just general direction for further researches, your help would be appreciated a lot.

**Comment by rauenzi** [comment] 2020-07-29 22:54
There is documentation on the requirements here https://github.com/rauenzi/BetterDiscordApp/wiki/Creating-Plugins

However there are not really tutorials, so we can leave this open as a potential enhancement to add a tutorial.

**Comment by MajorBarnulf** [comment] 2020-07-29 23:26
I think the most important would be to elaborate for a bit on observers in the scope of discordapp and their potential uses inside of the plugin, but I am not qualified enough to certify that.

**Comment by rauenzi** [comment] 2020-07-29 23:26
Observers would have the same scope and usage in discordapp as in any other usage of MutationObserver

**Comment by rauenzi** [comment] 2021-04-03 03:56
Are there any specific topics developers are looking to see covered?

**Comment by Farcrada** [comment] 2021-04-19 18:11
My first thoughts would go to:
- How do I use `BdApi`?
- What can I do?
- How do I explore?
- Where do I begin?

After that I'd say basic objectives, such as:
- How do I manipulate messages?
- How do I make things highlighted?
- How do I add extra information to an element reliably?

But also:
- How do I implement the most basic of keeping my plugin up to date?
(And that might even be one of the most important ones. To make sure that any edits or updates you make are being transferred to the users.)

Personally I've had to reverse engineer a lot of plugins to find out how any of it even worked. But that's probably mainly because I have never done anything advanced JavaScript (React?) related like this. Though with the help of other plugins, figuring out what requests gives which response and looking at the available options I've come to learn a lot; that and poking at the console with anything I could get my hands on.

And then into more advanced topics, like:
- Maybe adding a tutorial for how to "properly" setup a plugin with all the fancy routines you and Mirco have?
- A difference in what Zero's library entails and DevilBro's would also help. Together with what it adds on top of the normal `BdApi`. For this there'd be a use for a lot of detail, which might become more clear depending on the type of application/example that would be given.

Those are a few things I'm having in mind right now, but there's a lot to learn. It might even be worth starting with what a module is, What `props` are and maybe even how a `DisplayName` is derived. Just so the basics are down and people have something to rely on.

**Comment by Jkmcameron** [comment] 2021-07-06 10:23
>It might even be worth starting with what a module is, What `props` are and maybe even how a `DisplayName` is derived. Just so the basics are down and people have something to rely on.

Absolutely this. I have several years of tinkering in java and C++, I figured I'd have to learn the syntax of Javascript and then I'd be on my way making plugins but instead I'm stuck trying to make sense of 3 different APIs none of which offer any explanation of themselves any further than "look at the code and try to make sense of it" which would be fine if it weren't for the fact that nowhere can I find what a module is or what a property of a module is. I try to look at existing plugins to see how they do it and I find instances like `WebpackModules.getByProps('parse', 'parseTopic')` and am left wondering where the came up with these "Props" in the first place

**Comment by Puv1s** [comment] 2021-07-06 10:29
One thing is providing a plugin structure and syntax documentation but what you're saying is us essentially writing guides also for whole react, webpack and essentially full guide on reverse engineering... There are countless tutorials for those parts already.

**Comment by Jkmcameron** [comment] 2021-07-06 10:49
I have spent the last several hours searching up every possible combination of "Webpack" "React" "Javascript" etc. and have not found anything remotely close to what you're describing. I've even installed React Developer Tools so that I can view the React hierarchy of Discord which hasn't brought me any closer to understanding what is supposed to be passed to `BdApi.React`. If understanding Webpacks and React is truly the only thing preventing people from understanding BdApi, BDFDB, and ZeresPluginLibrary then surely it wouldn't be beneath everyone here to link beginners to some of these "countless tutorials"

**Comment by Jkmcameron** [comment] 2021-07-06 13:18
According to [this tutorial](https://www.digitalocean.com/community/tutorials/react-props#:~:text=If%20you're%20already%20familiar,main%20mechanism%20for%20component%20communication.) props are just a fancy term for parameters, and indeed that is the role they seem to take on. And yet when I look at `WebpackModules.getByProps('parse', 'parseTopic')` from the BetterCodeBlocks plugin or [any of these calls to `WebpackModules.getByProps` within ZeresPluginLibrary](https://rauenzi.github.io/BDPluginLibrary/docs/modules_discordmodules.js.html) it is imediately clear that you are passing fucntion names as "props". Somebody make sense of this.

**Comment by rauenzi** [comment] 2021-07-06 22:34
The props you linked are for a tutorial on React. But the function you are referring to (`WebpackModules.getByProps`) is in reference to Webpack and the Modules bundled by Discord as the name would suggest. It is a method to retrieve a module given a certain set of properties existing in the module. 

I think explaining React and Webpack themselves would be a bit out of scope of these tutorials as Pu said already. But their application in Discord's context is something we can cover.

**Comment by Jkmcameron** [comment] 2021-07-07 02:43
> As for your comments on the reverse engineering, it works the same in Discord as it does for any website. You can view the source for a given react component using the react developer tools and you can view Discord's source in the Chromium DevTools. Basic web development would also be out of scope of the planned tutorials and would be considered a prerequisite.

> If understanding Webpacks and React is truly the only thing preventing people from understanding BdApi, BDFDB, and ZeresPluginLibrary then surely it wouldn't be beneath everyone here to link beginners to some of these "countless tutorials"

**Comment by idgas01** [comment] 2021-07-08 17:30
This "tutorial" guide https://github.com/rauenzi/BetterDiscordApp/wiki/Creating-Plugins may be useful to experienced plugin developers, but not at all useful to beginners.  Why?  It's missing one thing.  A simple, working, example template.

If you look at this StackOverflow thread https://stackoverflow.com/questions/66929757/betterdiscord-how-do-i-make-a-plugin, one guy named Arjinoodles provided an example of a nonworking template.  I posted his code below at the bottom.  As you can see, this is so much more useful to me because it just has the barebone essentials and then you enter your code at the //your code line.  And if it doesn't work, then you go from there.  But at least you have a starting template.  I know that there are working plugins on the BetterDiscord website, but they are pages long with lots of code.  So I don't know what I can remove and what I can't.  That's why I need a barebones example.  Anyway, even though Arjinoodles only posted his example around three weeks ago, it is no longer working.  There is an error on the module.exports line where it says "class".  So I am thinking that the API or whatever has changed since three weeks ago.

But I know how this works.  The annoying, stuck up elites will tell me how stupid or wrong I am for wanting a simple, starting, example template.  Then lecture me on how everything I need is available and that I need to learn the stuff, yadda yadda.  And so I'm wasting my time by providing what I, as an individual, personally need and want.  I'm by no means all that knowledgeable about HTML, CSS, JavaScript, etc.  But somehow I managed to create around 50 working userscripts for Mozilla Firefox anyway.  For personal use.  And they worked and improved my life by 10 trillion percent.  And the reason that they worked is because I found barebone examples of what I needed and then just tweaked and did trial and error from there.  But your tutorial guide has nothing like that.  It's just an encyclopedia for experts.  Not at all noob friendly.  I'm not saying remove the encyclopedia.  I'm saying offer something in addition like what Arjinoodles provided below.  By the way, I tried contacting him on Reddit and no response, so I guess I'm SOL.  But yeah, I won't hold my breathe that you BD people will understand where I am coming from and be willing to provide what I want.  And even if you get the "majority" to agree with you, it doesn't make you right.  I know that there are people out there that are in the same shoes as I am.  And hopefully they will make their voice known.

```
 /**
 * @name PLugin Name
 * @version 0.0.1
 * @description Example Description
 * @author Username and/or tag
 *  
 */

   module.exports = class name{
     
       load() { }
       start() {

//your code

}
stop(){
  
}
}
```

**Comment by idgas01** [comment] 2021-07-08 17:33
Oh, and separate post, because different topic.  The plugin I was trying to create was to make a duplicate Friends List inside my server(s) at the bottom, underneath the channels.

I was going to try something like this (even though it's probably not the right code):

`$("div#ALL-tab").clone().appendTo("div#channels");`

**Comment by Puv1s** [comment] 2021-07-08 17:52
Regarding to the second post, this is completely out of topic for GitHub issue post.
First of all you should use  our discord server to discuss stuff like that.

**Comment by rauenzi** [comment] 2021-07-08 18:22
> This "tutorial" guide https://github.com/rauenzi/BetterDiscordApp/wiki/Creating-Plugins may be useful to experienced plugin developers, but not at all useful to beginners. Why? It's missing one thing. A simple, working, example template.

On the page you linked it says `Take a look at this Example for a template and description of each required and optional function.` This links you to the plugin template here https://gist.github.com/rauenzi/e5f4d02fc3085a53872b0236cd6f8225 (shown below for reference).
```js
/**
 * @name ExamplePlugin
 * @author YourName
 * @description Describe the basic functions. Maybe a support server link.
 * @version 0.0.1
 * @invite inviteCode
 * @authorId 51512151151651
 * @authorLink https://twitter.com/Whoever
 * @donate https://paypal.me/
 * @patreon https://patreon.com/
 * @website https://github.com/rauenzi/BetterDiscordApp
 * @source https://gist.github.com/rauenzi/e5f4d02fc3085a53872b0236cd6f8225
 */

module.exports = class ExamplePlugin {
    load() {} // Optional function. Called when the plugin is loaded in to memory

    start() {} // Required function. Called when the plugin is activated (including after reloads)
    stop() {} // Required function. Called when the plugin is deactivated

    observer(changes) {} // Optional function. Observer for the `document`. Better documentation than I can provide is found here: <https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver>
}
```

which when put into a valid plugin file (e.g. `test.plugin.js`), it loads and works as expected:
![Zx2xBK](https://user-images.githubusercontent.com/6865942/124971484-3d1a9300-dff7-11eb-80e0-07a3ef39386c.png)



> But I know how this works. The annoying, stuck up elites [...]

This really isn't the place for some psuedo-victim rant, especially when the plugin template you wanted exists and was linked on the page you referenced.


> Oh, and separate post, because different topic.

Different topics should go into different issues or discussed using a different more appropriate medium.

**Comment by idgas01** [comment] 2021-07-08 18:51
And just like I said before, there is an error...

> There is an error on the module.exports line where it says "class".

I tried following your exact steps, and now it is Line 15 Character 18.

![wscript_6U7OQnBQwo](https://user-images.githubusercontent.com/75463665/124975308-836df300-dff3-11eb-95c7-00d0bd6bd1a2.png)

![notepad++_QLzqvbuC6M](https://user-images.githubusercontent.com/75463665/124975318-8668e380-dff3-11eb-996b-d64703d14622.png)

**Comment by rauenzi** [comment] 2021-07-08 18:54
This is not a Microsoft JScript file and should not be run as such. The file should simply be placed in the plugin folder and BD will load it, as per usual.

**Comment by idgas01** [comment] 2021-07-08 18:57
The plugin is placed in the plugin folder.  And the plugin does show up in the list of plugins inside my Discord window.  But as soon as I click the blue Edit button, an error message appears.  The blue Edit button is a BetterDiscord button, is it not?  Why is a BetterDiscord button throwing an error for a BetterDiscord sample plugin?

![Discord_OjIELc1rbg](https://user-images.githubusercontent.com/75463665/124976008-53731f80-dff4-11eb-9adb-7d80c11950e2.png)

**Comment by idgas01** [comment] 2021-07-08 18:59
> The annoying, stuck up elites

Also, you've only confirmed this 20x since I wrote that.  I could copy and paste each line of text where you act like a stuckup and are annoying (hence my attitude).  But what good will it do?  You were born a jackass, you are a jackass, and you will always be a jackass.  Nothing will ever changed.  So it isn't a "pseudo victim rant".  It's the fcking truth.

**Comment by rauenzi** [comment] 2021-07-08 19:00
It tries to use your default editor, that means you have your default set to have all `.js` file run as Microsoft JScript. Issues with the edit button aren't related to this issue though.

**Comment by Puv1s** [comment] 2021-07-08 19:01
As zack said, issue on your end.
https://i.imgur.com/nKkin02.gif

You're complaining and making accusations that are false, and you should be asking about this in our support server first.

**Comment by idgas01** [comment] 2021-07-08 19:02
Thanks.  I changed default editors.

**Comment by rauenzi** [comment] 2021-07-08 19:05
>  (Maybe add this to the "tutorial"?)

There is no "tutorial" which is why this issue exists. The issue you experienced also affects regular end-users and not just developers. That's why there is an option to change how you want it to open in settings.

![Fvtxtt](https://user-images.githubusercontent.com/6865942/124976859-c8972280-dffd-11eb-8db4-879f29c89daf.png)

**Comment by Farcrada** [comment] 2021-07-08 22:16
So far I feel this topic has derailed far enough. It is clear there are some frustrations, however calling names or acting pretentious about existing wikis is not going to help anyone. It helps far more to be constructive in your feedback and leave aside the personal grudges you might have.

If you run into any issues with BetterDiscord there is always the green button if the issue you tested is found to be on BetterDiscord's end and the Support server ("Community" on http://betterdiscord.app/) if you simply run into issues and would like some help. There too it helps to be constructive and leave the extra's out. Be concise, to the point and constructive; something we can work with.

### So I wish to bring it back on track with the question posed:

> 
> Are there any specific topics developers are looking to see covered?

**Comment by ilexite** [comment] 2021-12-28 20:22
Hello, I know I am a little bit late to this issue, but I would like to answer the following question:
> Are there any specific topics developers are looking to see covered?
Personally, I think these topics should be covered:
- `BdApi` methods
  - `findModuleByProps(...)` and other similar methods
- How to use `BdApi.React`
- Common Webpack functions
  - `sendMessage`
  - `receiveMessage`
  - `sendBotMessage`
  - `get<Channel,Guild,User>Id`
- Best practices
- Commented examples of basic but (optionally) useful plugins
- Plugin development FAQ
Feel free to add to my list if you think I missed something.

**Comment by rauenzi** [comment] 2022-08-05 04:16
Our first iteration is available under the plugin basics section at https://docs.betterdiscord.app

**Closed by rauenzi** 2022-08-05 04:16 UTC
Labels: enhancement
