### ISSUE TITLE
BD not allowing themes/plugins [Bug]

### ISSUE THREAD

**Issue by solarwoofs** [BetterDiscord/BetterDiscord#1101] opened 2021-11-01 21:24 UTC
**Describe the Bug**
After restarting my laptop, BD no longer allowed me to use themes/plugins. BD's setting tab is there, with all the settings options expected, but there's no tabs for plugins or themes, and I cannot use plugins or themes at all.

**To Reproduce**
Update BD to latest from installer and open Discord.

**Expected Behavior**
My themes and plugins to activate, and have tabs for themes/plugins.

**Screenshots**
https://cdn.discordapp.com/attachments/881037029826232320/904832480778002432/unknown.png

**Discord Version**
Latest stable (I can't find a version number, but the Changelog says October 4th, 2021.)

**Additional Context**
To try fixing the issue, I uninstalled and reinstalled Discord & BD (while also making sure to clear out left behind files), it didn't work. I tried to repair BD using the installer, but it didn't work. I tried finding the file path for BD's plugins/themes and inserting the files into there, to see if it would force them to activate, but it also did nothing.

**Comment by dav1312** [comment] 2021-11-01 21:25
Duplicate of #1099

**Closed** 2021-11-15 00:36 UTC
Labels: bug
