### ISSUE TITLE
[Feature] set plugins/themes directories somewhere else

### ISSUE THREAD

**Issue by wael444** [BetterDiscord/BetterDiscord#899] opened 2021-07-13 03:40 UTC
**Is your feature request related to a problem? Please describe.**

"I'm always frustrated when" i have to constantly move my plugins and themes around in my .config or AppData due to the fact that i constantly reinstall my operating system, though i can try to symlink the directories to somewhere else as i can do that in linux or just live with it i suppose.

**Describe the feature you'd like**

be able to set the plugins and themes directories somewhere else (eg. D:\BetterDiscord\themes or /mnt/Betterdiscord/plugins)

**Comment by rauenzi** [comment] 2021-07-13 13:56
Duplicate of #539

**Closed by rauenzi** 2021-07-13 13:56 UTC
Labels: enhancement
