### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JorgeCepeda** [BetterDiscord/BetterDiscord#1181] opened 2022-01-25 17:45 UTC
**Describe the Bug**
The Hide GIF picker button in BD Settings broke

**To Reproduce**
Activate the Hide GIF picker button

**Expected Behavior**
The Hide GIF picker button hides or shows depending on the button's state

**Screenshots**
![Captura](https://user-images.githubusercontent.com/69733604/151030466-32d69fab-38f8-44db-9e01-8c9e2ac784ab.PNG)

**Discord Version**
Stable

**Additional Context**
The Stickers button is hidden using additional unrelated CSS

**Comment by dav1312** [comment] 2022-01-25 18:09
Duplicate of #841

**Comment by SmolAlli** [comment] 2022-01-26 01:13
[Use this plugin instead](https://betterdiscord.app/Download?id=383)

**Closed** 2022-02-04 20:49 UTC
Labels: bug
