### ISSUE TITLE
[crashing when I attempt to click on the emoji button]

### ISSUE THREAD

**Issue by Tindi12** [BetterDiscord/BetterDiscord#1117] opened 2021-11-12 00:42 UTC
**Description of  Bug**
It shows a you died and got slaughtered by an error level  9000.... exactly after I click on either one of both the emoji and gif buttons.

**Discord Version**
Stable

**Additional Context**
 I don't have any plugins installed. I only have one theme installed (clear-vision v6.1.3).
 I have restarted discord, I have also repaired better discord, and have tried reinstalling.
  nothing still works. :(

**What shows when I click on the emoji/gif button:**
![Annotation 2021-11-12 100237](https://user-images.githubusercontent.com/66786932/141388760-1a433629-50c9-47f9-a1a3-a997909a3ea3.png)

**Comment by doggybootsy** [comment] 2021-11-12 00:45
there's already a issue on this 
Look at this ![image](https://user-images.githubusercontent.com/71196819/141389426-83addeb7-e9e5-4251-8ce9-8b86b101ed93.jpeg)

**Comment by rauenzi** [comment] 2021-11-12 00:45
Duplicate of literally the previous issue #1116

**Closed by rauenzi** 2021-11-12 00:45 UTC
Labels: bug
