### ISSUE TITLE
Have a web extension and userscript for BetterDiscord

### ISSUE THREAD

**Issue by Coding4Hours** [BetterDiscord/BetterDiscord#1757] opened 2024-06-08 02:40 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

I want a extension for the betterdiscord and a usersciprt

**Comment by aikooo7** [comment] 2024-06-28 17:56
Duplicate of #350 and #1245

**Comment by Coding4Hours** [comment] 2024-07-06 03:19
okey

**Closed** 2024-07-07 03:35 UTC
Labels: enhancement
