### ISSUE TITLE
[Bug] "You Died" screen when entering the gif menu for the chats

### ISSUE THREAD

**Issue by ExtremeJose** [BetterDiscord/BetterDiscord#1118] opened 2021-11-12 13:23 UTC
**Describe the Bug**
When pressing the gif menu in the bottom right hand corner a screen with big letters spelling "You Died" appears with the text "Looks like you were slaughtered by an Error level 9000. Might have been one of your plugins?

**To Reproduce**
 Click the gifs in the chat box

**Expected Behavior**
 The "You Died" screen pops up

**Screenshots**

![You Died](https://user-images.githubusercontent.com/94178924/141473823-281638f1-f446-4711-b2f9-3be8e5eceac7.png)

**Discord Version**
 Stable BD 1.2.4

**Additional Context**
 I don't have StatusEverywhere

**Comment by SmolAlli** [comment] 2021-11-12 13:24
Duplicate of #1116

**Closed** 2021-11-12 19:33 UTC
Labels: bug
