### ISSUE TITLE
[Bug] Crashes when trying to use the GIF option in chat

### ISSUE THREAD

**Issue by KitKatze** [BetterDiscord/BetterDiscord#1126] opened 2021-11-13 23:42 UTC
**Describe the Bug**
My discord gives a Level 9000 error when I try to use the GIF's from discord.

**To Reproduce**
Click on the GIF option in chat (Direct Message or in Server)

**Expected Behavior**
Opens the GIF section normally but it crashes instead

**Screenshots**
![image](https://user-images.githubusercontent.com/94260994/141662063-7a2fce87-4871-4edb-8030-5ad76dff7128.png)

**Discord Version**
Stable. BD v1.2.4

**Additional Context**
I only use themes and have no Plugins installed and it only started happening after I updated my drivers with ccleaner

**Comment by dav1312** [comment] 2021-11-13 23:43
Duplicate of #1116

**Closed** 2021-11-13 23:49 UTC
Labels: bug
