### ISSUE TITLE
[Bug] Bug when I want to publish a gif or emoji

### ISSUE THREAD

**Issue by NekoKawaii666** [BetterDiscord/BetterDiscord#1124] opened 2021-11-13 05:06 UTC
I already try to remove the plugging put them back I even try to disable them and the ractivé check the updates it does not work

This does this when I click on Emoji or Gif

**Comment by NekoKawaii666** [comment] 2021-11-13 05:06
![image](https://user-images.githubusercontent.com/94212323/141606435-912ddbcf-c875-4ae1-85ed-8a8d32767547.png)

**Comment by SmolAlli** [comment] 2021-11-13 05:14
Duplicate of #1116

**Closed** 2021-11-13 09:12 UTC
Labels: bug
