### ISSUE TITLE
unable to install[Bug]

### ISSUE THREAD

**Issue by xxtraspicyy** [BetterDiscord/BetterDiscord#1545] opened 2023-02-28 11:49 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I download the installer and open the .exe file and a blank box appears with nothing else 
![image_2023-02-28_224533694](https://user-images.githubusercontent.com/93108606/221845086-f9cb4aeb-47dc-403f-83ae-e85da1ccac66.png)

### Expected Behavior

when clicking on the installer It is meant to open with the installer instructions etc as it has previously done 

### Steps To Reproduce

download the exe file 
open the exe file 

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

previously had betterdiscord earlier in the day. I was advised by a pop up when opening discord and attempting to fix betterdiscord due to an alternative issue there was an updated version, attempted to install the updated version was unsuccessful 
I was unable to be heard in a VC so uninstalled all discord files and deleted all files from roaming and local on my pc then reinstalled discord and betterdiscord, since then I have gotten the black box issue as attached when trying to install betterdiscord

**Comment by rauenzi** [comment] 2023-03-01 21:56
Duplicate of https://github.com/BetterDiscord/Installer/issues/310

**Closed by rauenzi** 2023-03-01 21:56 UTC
Labels: bug
