### ISSUE TITLE
BetterDiscord "This is Awkward" screen when using emoji, gif, or sticker menu.

### ISSUE THREAD

**Issue by Define-me** [BetterDiscord/BetterDiscord#1122] opened 2021-11-12 16:02 UTC
Anytime you click on the Emoji, Sticker, or Gif buttons on discord betterdiscord will crash and send you to the "This is awkward" screen.

**Comment by dav1312** [comment] 2021-11-12 16:03
Duplicate of #1116

**Closed** 2021-11-12 16:11 UTC

**Comment by SdkKKK** [comment] 2021-11-14 15:23
> Anytime you click on the Emoji, Sticker, or Gif buttons on discord betterdiscord will crash and send you to the "This is awkward" screen.

So I had this same issue with the discord crashing in every try to use the emoji menu or any other option in the text bar, I found a solution to this.

Here's the instruction. 

go to C:\Users\_____\AppData\Roaming\BetterDiscord\data\stable (if you can't find it then idk)

Then open emotes.json and paste this 

{
    "general": {
        "download": true,
        "emoteMenu": false,
        "hideEmojiMenu": false,
        "modifiers": true,
        "animateOnHover": false
    },
    "categories": {
        "twitchglobal": true,
        "twitchsubscriber": false,
        "frankerfacez": true,
        "bttv": true
    }
}

then save the file and restart discord.

You're good to go.
