### ISSUE TITLE
[Bug] BetterDiscord stops working and has to be repaired every time Discord updates

### ISSUE THREAD

**Issue by CookieGuy123** [BetterDiscord/BetterDiscord#1665] opened 2023-09-05 21:13 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Whenever Discord updates itself, BetterDiscord stops initializing and has to be repaired for it to work. It's pretty annoying to have to redownload the installer and reinstall BD.

### Expected Behavior

BD should initialize whenever Discord is opened after an update.

### Steps To Reproduce

1. Have a Discord update install
2. BD won't initialize, and you'll have to reinstall.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.9.3

**Comment by fowlis** [comment] 2023-09-05 21:20
1. This happens because Discord updates refresh the files that BetterDiscord injects to.
2. You do not need to redownload the installer unless there is an update available for the installer.
3. If this happens more than once every couple months, I'd suggest doing a clean reinstall of your client - unless you are on canary, in which case you'll just have to deal with it because of how often canary updates.

**Comment by CookieGuy123** [comment] 2023-09-06 15:55
@fowlis 1. So there's no way for BD to detect and change those files?
2. I do need to redownload the installer to use the 'repair' function so BD works agin.
3. I have already done that lots of times, but it still stops working after update
4. I never said that BD should check for being uninstalled or that it auto-reinstalls itself. I said that I would need the installer to use the repair function (which reinstalls BD)

**Comment by fowlis** [comment] 2023-09-06 16:05
1. No. BetterDiscord doesn't constantly run on your system and check for the files changing. I also said this in my original 4th point
2. If you are deleting the installer after use, yes you will need to redownload it. But unless you need that 30mb of space back there is no reason to delete the installer if you're going to use it again.
3. Reinstalling Discord will not fix this "issue", unless it's occurring more frequently than Discord actually updates.

**Comment by rauenzi** [comment] 2023-09-06 20:26
We are considering changing our injection method which could _potentially_ allow us to hook into the updater, but there's no guarantees

**Comment by mitchcapper** [comment] 2023-10-25 06:36
Something else to consider would be a custom discord launcher that checks the injected files prior to launching discord. If you use the launcher to start your discord instance you don't have to manually do the reinstalls for each discord instance.   Wouldn't be required (normal launcher would still work) but an option for users.  Yes it adds an app over just running inside the electron instance but it could clearly be quite minimal.  To avoid duplicating logic it could launch the installer with a quiet/instance specifier as well to make it fairly seamless.

**Comment by rauenzi** [comment] 2023-10-25 13:39
Yes this is something we are aware of and have been discussing

**Comment by jhones-dev** [comment] 2023-10-25 15:47
So annoying, I basically have to reinstall every single time that i open discord. When I reinstall better discord, it opens with all plugins enabled. If I simply open discord (without going by the installer), it doesn't work.

**Comment by rauenzi** [comment] 2024-02-22 05:23
Duplicate of #1231

**Closed** 2024-02-22 05:23 UTC
Labels: bug
