### ISSUE TITLE
[Bug] Crash after clicking on someone with RMB

### ISSUE THREAD

**Issue by mih0ww** [BetterDiscord/BetterDiscord#1550] opened 2023-02-28 19:40 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

Whenever I click on someone from server list with RMB the same error appears as the one that appeared when opening Settings. 

### Expected Behavior

Being able to RMB someone as it used to

### Steps To Reproduce

1. Open Discord
2. Go to a server
3. Click on anyone from the list on the right with your right mouse button
![1](https://user-images.githubusercontent.com/126590264/221959622-b08f5d54-5915-43ed-baec-f444397463b5.png)

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

Earlier today I had the same issue but with the Settings, then I used @echo and #!/bin/sh commands from comments in #1540 which solved the Settings error, but seems like it made a new one.

**Comment by Aida-Enna** [comment] 2023-02-28 20:56
This seems to happen with plugins that add to the context menu (the right click menu). You could try disabling them for the moment. I'm not sure if that's a plugin needing to be updated or BD itself.

**Comment by mih0ww** [comment] 2023-02-28 21:21
@Aida-Enna I disabled BetterVolume plugin and it worked, but it's weird because I've been using it for the past couple months, and I believe there was no update in the last couple of days. Thanks anyway, it actually was caused by a plugin and that's my bad

**Comment by RSPadilha** [comment] 2023-03-01 00:45
I have the same issue but cannot go to the settings because it crashes too
![discord crash](https://user-images.githubusercontent.com/15999460/222016100-d2ec51a3-d0c3-44a6-958f-0eb89a8834f3.png)

**Comment by kamikadzew** [comment] 2023-03-01 00:55
You can change name of the plugin folder or just the problematic plugin. The folder is  %appdata%/BetterDiscord/plugins on Windows.

**Comment by Frumpy9** [comment] 2023-03-01 01:42
> You can change name of the plugin folder or just the problematic plugin. The folder is %appdata%/BetterDiscord/plugins on Windows.

I had the same issue with a fresh install of BD with no plugins or themes. Discord only started working when I uninstalled BD.

**Comment by DerpDerpingtonIsHere** [comment] 2023-03-01 02:21
I have removed all plugins and crashes are happening. This seems to be a betterdiscord issue in itself.

**Comment by Violet-Scarelli** [comment] 2023-03-01 04:50
Having the same issue.

**Comment by AK-Rezina** [comment] 2023-03-01 04:53
Excuse me for the sidebar.
In my environment, RMB is fine, but when I try to go to the settings page, it seems impossible.
Also, when I put in QuickMention.plugin.js, it crashes as soon as I put it in.

**Comment by Hixelite** [comment] 2023-03-01 12:58
It also crashes when you go to the user settings. I removed all plugins from plugins folder including themes. It still crashes when going to the user settings.

**Comment by callmeyonggor** [comment] 2023-03-01 13:07
Up. Mine also crash when right click my friend in voice channel

**Comment by aqtsalt** [comment] 2023-03-01 15:31
same

**Comment by mih0ww** [comment] 2023-03-01 16:10
@callmeyonggor @aqtsalt 
Have you tried disabling some of the plugins to see which one causes this? For all of the plugins I'm using which are BetterVolume, GameActivityToggle and ReadAllNotificationsButton it was the BetterVolume triggering the bug.

**Comment by callmeyonggor** [comment] 2023-03-01 16:21
> @callmeyonggor @aqtsalt Have you tried disabling some of the plugins to see which one causes this? For all of the plugins I'm using which are BetterVolume, GameActivityToggle and ReadAllNotificationsButton it was the BetterVolume triggering the bug.

Yup i did disable BetterVolume too but still not working

**Comment by rocwaj** [comment] 2023-03-01 17:26
i got same problem. Discord crashes when i click on the settings button

**Comment by shiseni** [comment] 2023-03-01 19:32
> i got same problem. Discord crashes when i click on the settings button. Even though i have an empty plugins folder and in general just installed betterdiscord after cleaning up the old folders

https://github.com/BetterDiscord/BetterDiscord/issues/1546#issuecomment-1448904244

**Comment by Aida-Enna** [comment] 2023-03-01 19:37
From what I can tell, there are 3 major crashes happening:

1) When you load a channel with certain plugins that modify/read/manage/mess with messages, it can crash. Restarting discord will put it in a loop of loading the channel -> crashing over and over. Rename the plugins folder, start discord again, and slowly add in plugins, enabling each one until it crashes again. That's your problematic one.

2) When you click the settings button, BD crashes. The fix for it isn't available in the distributed build yet, but you can fix it yourself via https://github.com/BetterDiscord/BetterDiscord/issues/1546#issuecomment-1448904244 (as shiseni referenced above)

3) Crashing when right clicking - This is typically caused by plugins that add their own menus/items to the right click context menu. You can identify these in the same way as the first one. Rename the plugins folder, start discord again, and slowly add in plugins, enabling each one until right clicking on the item crashes again. That's your problematic one.

**Comment by rauenzi** [comment] 2023-03-01 21:50
This has been fixed in the latest release

**Closed by rauenzi** 2023-03-01 21:50 UTC
Labels: bug
