### ISSUE TITLE
[Bug] Crash when clicking on nested menu

### ISSUE THREAD

**Issue by jareddo-kun** [BetterDiscord/BetterDiscord#1246] opened 2022-03-02 12:23 UTC
**Describe the Bug**
Discord crashes when I click on nested plugin error list

**To Reproduce**
1. Have an extension with error (maybe this also applies with the other menus like these)
2. Click on drop-down arrow

**Expected Behavior**
Show details under the block

**Screenshots**
![How to reproduce](https://user-images.githubusercontent.com/72799720/156360636-bd79ff20-99eb-4fcf-8472-f032423488d6.gif)

**Version**
Stable 116961 (5fb0703)
BetterDiscord 1.5.2
Windows 10 64-Bit (10.0.19044)

**Comment by QbDesu** [comment] 2022-03-08 01:22
Can reproduce
```log
TypeError: Cannot read property 'divider' of undefined
    at Object.get Divider [as Divider] (<anonymous>:4:235077)
    at Object.value (<anonymous>:4:203509)
    at Object.get (<anonymous>:4:203182)
    at Object.get (<anonymous>:4:235716)
    at renderErrorBody (<anonymous>:4:239450)
    at render (<anonymous>:4:240990)
```
Error probably happens here because the Divider module isn't found anymore: https://github.com/BetterDiscord/BetterDiscord/blob/main/renderer/src/ui/addonerrormodal.jsx#L24

**Comment by Tropix126** [comment] 2022-03-24 16:12
I actually could reproduce this issue on a build override I installed about a week ago, but it suddenly fixed itself on the latest canary build. Strange.

Anyways, it would probably be best if we just used our own divider styling.

**Comment by rauenzi** [comment] 2022-04-23 04:31
This is a duplicate of #1229

**Closed by rauenzi** 2022-04-23 04:31 UTC
Labels: bug
