### ISSUE TITLE
Better Discord Broken Again Due To Discord Latest Update

### ISSUE THREAD

**Issue by IXSENPA1XI** [BetterDiscord/BetterDiscord#1407] opened 2022-09-27 01:44 UTC
The Better Discord Apt Wont Install At All Please Fix It

**Comment by Clone1336** [comment] 2022-09-27 01:46
I don't understand what the joke is, the BD just doesn't work, it doesn't turn on when you start a regular DS.

**Comment by SmolAlli** [comment] 2022-09-27 01:54
duplicate of #1404

**Closed** 2022-09-27 16:59 UTC
