### ISSUE TITLE
[Bug] Can't completely close Discord

### ISSUE THREAD

**Issue by bestpika** [BetterDiscord/BetterDiscord#1358] opened 2022-08-03 05:01 UTC
**Describe the Bug**

When I close Discord, two processes do not close properly, and one of them uses CPU.

**To Reproduce**

1. Open Discord and wait for the load to complete.
1. Close Discord.

**Expected Behavior**

All Discord processes should end.

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/182528011-c779b7dd-7f70-441b-95ef-3b1c781ce628.png)

**Discord Version**

- Stable

**Additional Context**

Discord with a clean installation "does not have this problem".
This problem only occurs "after BetterDisocrd is installed" and will persist even if I remove BetterDiscord.

**Comment by SmolAlli** [comment] 2022-08-03 05:02
Are you sure this is a BetterDiscord issue? Did you test after uninstalling BD and experienced the expected behaviour?

**Comment by bestpika** [comment] 2022-08-03 05:06
@SmolAlli It didn't happen before 1.5.3-hotfix1, and if it's Discord's own process that's stuck, I should be stuck at the loading screen the next time I run it.

**Comment by qwerasd205** [comment] 2022-08-03 05:07
> @SmolAlli It didn't happen before 1.5.3-hotfix1, and if it's Discord's own process that's stuck, I should be stuck at the loading screen the next time I run it.

So, no, then, you haven't verified that this doesn't happen without BD installed. Please do that and report back.

**Comment by bestpika** [comment] 2022-08-03 05:12
@qwerasd205 Sorry my description was not clear enough.
I have tried to remove Discord and BetterDiscord completely.
As long as I have "previously installed" BetterDiscord, the program still gets stuck even if I remove BetterDiscord.
I had to remove and reinstall Discord to avoid this.

**Comment by qwerasd205** [comment] 2022-08-03 05:16
Did you try opening and closing vanilla Discord several times? It seems rather unlikely that haivng BD installed, much less having "previously installed" BD would cause an issue like this.

**Comment by bestpika** [comment] 2022-08-03 05:19
@qwerasd205 I have added the relevant information to the front.

**Comment by qwerasd205** [comment] 2022-08-03 05:20
You have not noted whether you have attempted several closes and opens on a "clean installation" of Discord.

**Comment by bestpika** [comment] 2022-08-03 05:23
I'm certainly trying before I say anything.
Do I have to tell you how many times I turned it open or closed it?

**Comment by qwerasd205** [comment] 2022-08-03 05:26
I'm just trying to get the simple stuff out of the way so we don't waste our time trying to debug a problem that isn't caused by BD.

**Comment by rauenzi** [comment] 2022-08-03 05:30
> will persist even if I remove BetterDiscord.

How are you removing it? If via the installer, then BD is not affecting the install and no longer can.

**Comment by rauenzi** [comment] 2022-08-03 05:32
Also please include some detailed version information.

**Comment by qwerasd205** [comment] 2022-08-03 05:41
Detailed version information can be found at the bottom of the scroller in the User Settings of your Discord.
<img width="500" alt="detailed_info" src="https://user-images.githubusercontent.com/7241851/182532279-6992d5df-07f1-4845-bfd0-cd586e9950bf.png">

**Comment by bestpika** [comment] 2022-08-03 06:15
I just did a few more tests, and it didn't work until I deleted the "AppData\Roaming\BetterDiscord\data\ptb" folder.
I was using ptb version before, but it kept crashing after updating hotfix1, so I removed ptb version and installed stable version.

I remembered to delete the stable setting every time I removed BetterDiscord when I was testing it, but I didn't notice that the ptb setting was still there.
But I can't reproduce it now because I've removed the ptb settings.
I really do not want to continue to spend time here, since you can not reproduce it, then take it as no problem.

**Comment by rauenzi** [comment] 2022-08-09 22:23
Please see if this still happens with the latest version, I am curious.

**Closed by rauenzi** 2022-08-09 22:23 UTC
Labels: bug, can't reproduce
