### ISSUE TITLE
[Bug] Lots of plugins throwing errors with "TypeError: Illegal invocation"

### ISSUE THREAD

**Issue by theS1LV3R** [BetterDiscord/BetterDiscord#1634] opened 2023-06-14 09:09 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

After a recent update either to discord or betterdiscord, unsure which one, a lot of common plugins and plugins I've been using fine have been failing to load with the following error:

Also a lot of plugins that aren't erroring that just seem to not be loaded

```js
Module filter threw an exception. <some function> TypeError: Illegal invocation
    at filter (RoleMentionIcons.plugin.js:275:31)
    at renderer.js:4:45556
    at s.getModule (renderer.js:4:46588)
    at Object.getModule (renderer.js:4:366305)
	  <<variable lines of plugin stack trace>>
    at A.requireAddon (renderer.js:4:35124)
    at A.loadAddon (renderer.js:4:7625)
    at A.loadAddon (renderer.js:4:32796)
    at A.loadAllAddons (renderer.js:4:10099)
    at A.initialize (renderer.js:4:4521)
    at A.initialize (renderer.js:4:31995)
    at Object.startup (renderer.js:4:357022)
```

### Expected Behavior

Plugins load fine

### Steps To Reproduce

1. Install discord as usual
2. Add a plugin, e.g. [ShowAllActivities](https://betterdiscord.app/plugin/ShowAllActivities)
3. Observe

### Operating System

Linux

### Discord Version

PTB

### BetterDiscord Version

v1.9.2

**Comment by TheCommieAxolotl** [comment] 2023-08-19 03:23
This is an issue with the Webpack searcher in question. It is caused by discord exporting DOMTokenList in one of their modules, this has already been fixed in BD in [022b8fa](https://github.com/BetterDiscord/BetterDiscord/commit/022b8fa38095b7b7fb8b2e6583f73cf95440ca01).

**Closed** 2023-08-29 03:54 UTC
Labels: bug
