### ISSUE TITLE
[Feature] Support Discord Development

### ISSUE THREAD

**Issue by kkrypt0nn** [BetterDiscord/BetterDiscord#992] opened 2021-08-13 18:07 UTC
**Is your feature request related to a problem? Please describe.**
I use the Discord Development version because it has a dark icon, it's running the same build as Discord Canary, and sadly I can't use BetterDiscord.

**Describe the feature you'd like**
Add support to the Discord Development app.

![image](https://user-images.githubusercontent.com/43011723/129401297-030ba649-930e-42c9-9bf9-bdb29773975d.png)
*Currently have Discord Development installed*

**Comment by rauenzi** [comment] 2021-08-13 18:25
Duplicate of #520

**Closed by rauenzi** 2021-08-13 18:25 UTC
Labels: enhancement
