### ISSUE TITLE
[Feature] Enable/disable all plugins one toggle

### ISSUE THREAD

**Issue by ZenMasta** [BetterDiscord/BetterDiscord#1684] opened 2023-10-26 18:51 UTC
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature you'd like!

With the frequency of discord breaking stuff. It would be nice if after repair installing BD, there was a toggle to enable all plugins instead of doing them one at a time.

**Comment by fowlis** [comment] 2023-10-26 18:52
It's intended behaviour with the repair option to disable all your plugins. Run the install option if you want to keep them enabled.

**Comment by rauenzi** [comment] 2023-10-26 18:58
Duplicate of #723

**Closed by rauenzi** 2023-10-26 18:58 UTC
Labels: enhancement
