### ISSUE TITLE
Custom CSS to work in pop outs.

### ISSUE THREAD

**Issue by mjames74** [BetterDiscord/BetterDiscord#943] opened 2021-07-19 21:12 UTC
I was trying to edit the background of the call screen to green for chroma key for streaming. I was able to find the class and edit it. And it does make the main video call screen green, but it does not apply it to the video call window if popped out.

If I use the console on the pop out window and apply the same edit to the same class in my custom css, it will work. So they both use the same class, it just isn't applied on pop outs. The class just for reference is:

.wrapper-2qzCYF {
   background-color: green;
}

![10cd1406c48e1b2cd7d3eaeeccd48e5a](https://user-images.githubusercontent.com/15372951/126227941-95f86fdc-8c25-4cc5-8428-8071af0174ce.png)

**Comment by doggybootsy** [comment] 2021-07-19 21:17
This would be a duplicate of https://github.com/BetterDiscord/BetterDiscord/issues/464

**Comment by rauenzi** [comment] 2021-07-19 21:43
See above

**Closed by rauenzi** 2021-07-19 21:43 UTC
Labels: enhancement
