### ISSUE TITLE
[Bug] BetterDiscord injects to wrong subdirectory

### ISSUE THREAD

**Issue by esibun** [BetterDiscord/BetterDiscord#1131] opened 2021-11-16 19:46 UTC
**Describe the Bug**
The BetterDiscord injector is creating a subdirectory in the discord_desktop_core module folder instead of modifying the correct file.  This is preventing BetterDiscord from loading at start since the subdirectory is never read by discord.

**To Reproduce**
(on Gentoo if it matters)
_clone repo_
npm run build
npm run inject

**Expected Behavior**
BetterDiscord should modify the existing files in the discord_desktop_core directory

**Actual Behavior**
BetterDiscord creates a *new* folder in the discord_desktop_core and places files within the subdirectory.

**Screenshots**
![Directory after injection](https://ss.esibun.net/Screenshot_20211116_141959.jpeg)

**Discord Version**
Discord (Stable) v0.0.16, BetterDiscord v1.3.0

**Additional Context**
"app" subdirectory created here: https://github.com/BetterDiscord/BetterDiscord/blob/main/scripts/inject.js#L53
It looks like this might be a new behavior of the discord installer as this was a fresh install of 0.0.16.  I think it would be better to check if core.asar exists in the directory prior to making the app subdirectory.

I am currently working around this by manually copying the files from app to the parent directory, however this does break the injector.

**Comment by rauenzi** [comment] 2021-11-16 19:50
The inject script is indeed broken on linux, duplicate of #1069

**Closed by rauenzi** 2021-11-16 19:50 UTC
Labels: bug
