### ISSUE TITLE
[Feature] Automatic repair after a discord update

### ISSUE THREAD

**Issue by NukeThief** [BetterDiscord/BetterDiscord#1233] opened 2022-02-19 12:02 UTC
it would be super useful beacuse discord has stepped up the game of blocing custom clients

**Comment by SmolAlli** [comment] 2022-02-19 12:19
Duplicate of #1231 
Also, Discord has not "stepped up their game". They just changed the folder the Discord files reside in. This has happened before, it will happen again, and BetterDiscord is more than capable of easily being fixed just by reinstalling.

**Closed** 2022-04-23 04:31 UTC
Labels: enhancement
