### ISSUE TITLE
[Feature] Support Discord Development Version

### ISSUE THREAD

**Issue by andhra21231** [BetterDiscord/BetterDiscord#1254] opened 2022-03-23 03:00 UTC
**Is your feature request related to a problem? Please describe.**
I can't Download Better Discord using Discord Development Version

**Describe the feature you'd like**
Adding Support to Discord Development Version

**Additional context**
Discord Development Context: https://discord.com/api/downloads/distributions/app/installers/latest?channel=development&platform=win&arch=x86

**Comment by SmolAlli** [comment] 2022-03-23 03:02
Duplicate of #520

**Closed** 2022-03-23 03:09 UTC
Labels: enhancement
