### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DataRedact** [BetterDiscord/BetterDiscord#913] opened 2021-07-17 09:37 UTC
**Describe the Bug**
Better Discord does not allow screen sharing to work in general.

**To Reproduce**
Install Better Discord
Join a voice call
Try to screen share

**Expected Behavior**
It should show your screen

**Screenshots**

<img width="545" alt="Screenshot 2021-07-17 at 10 34 04" src="https://user-images.githubusercontent.com/58233991/126032795-bc26eb48-41aa-43d0-aa10-9ee6535d4b5a.png">
Note: This is trying to stream a window, not whole screen. When I try whole screen, the stream opens then instantly closes like I closed it.
**Discord Version**
Stable

**Additional Context**
M1 Macbook Air
Big sur 11.4
Streaming a window makes the stream perpetually load, and trying to stream whole screen just instantly closes the stream and asks for feedback on the stream which only usually comes when you yourself close it. Tried reinstalling - stream only worked with a clean discord without BD. Tried to repair - still didn't work.

**Comment by DataRedact** [comment] 2021-07-17 09:39
https://streamable.com/e18qi0

What happens when you try to stream whole screen

**Comment by rauenzi** [comment] 2021-07-27 17:22
Duplicate of #889

**Closed by rauenzi** 2021-07-27 17:22 UTC
Labels: bug
