### ISSUE TITLE
Apple silicone M1 not compatible

### ISSUE THREAD

**Issue by DanielAbsi** [BetterDiscord/BetterDiscord#1321] opened 2022-06-17 14:43 UTC
I use an apple Apple silicone M1 and BetterDiscord is unable to work on my apple silicone M1

**Comment by maenDisease** [comment] 2022-06-17 14:54
It works on my M1 MacBook Air

**Comment by Vendetta-Does-Stuff** [comment] 2022-06-17 18:31
It works perfectly on my m1 MacBook, it's a problem on your end not a bug for all m1 macs.

**Comment by SmolAlli** [comment] 2022-06-17 22:48
you have also provided no information on what your issue is. please close this and get some support from here - https://betterdiscord.app/invite

**Closed** 2022-06-24 21:41 UTC
Labels: bug
