### ISSUE TITLE
[Bug]Have trouble inject betterdiscord to discord-canary downloaded by snap store

### ISSUE THREAD

**Issue by backryun** [BetterDiscord/BetterDiscord#1156] opened 2022-01-01 19:19 UTC
**Describe the Bug**

The injector.js can`t find discord location when installed by snap store.

**To Reproduce**

1. install discord-canary on snap store.
2. build betterdiscord by git source compile.
3. try it inject betterdiscord use command: npm run inject canary
4. you can see inject.js can`t find discord where it is.

**Expected Behavior**

I just want betterdiscord recognize discord-canary where it is.

**Screenshots**

![image](https://user-images.githubusercontent.com/24198422/147858485-60b13680-3936-402f-8a00-484c0b704915.png)

**Discord Version**

Canary

**Additional Context**

I`m using fedora kde 35.
and discord-canary installed from snap store.
the discord location is /var/lib/snapd/snap/discord-canary/current/usr/share/discord-canary/DiscordCanary
Please help what do i do.

**Comment by ForBai** [comment] 2022-01-11 13:23
you can use https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by rauenzi** [comment] 2022-01-24 06:33
Duplicate of #679

**Closed by rauenzi** 2022-01-24 06:33 UTC
Labels: bug
