### ISSUE TITLE
[Bug] Better Discord Broken on Discord Canary on MacOS M1

### ISSUE THREAD

**Issue by MahdeenSky** [BetterDiscord/BetterDiscord#1266] opened 2022-04-10 03:17 UTC
**Describe the Bug**

 Better Discord Broken on Discord Canary. Does not start in Better Discord, only opens regular discord.

**To Reproduce**

Install latest discord canary and then run better discord install, open discord, nothing happens.

**Expected Behavior**

Better discord working.

**Screenshots**

**Discord Version**

Canary 123387 (14782d3) Host 0.0.283 OS X 10.15.7 (20.6.0)

**Additional Context**

Probably something about the latest discord broke better discord and now it doesn't work

**Comment by TheCommieAxolotl** [comment] 2022-04-10 03:19
Duplicate of #1265

**Comment by alsoGAMER** [comment] 2022-04-12 10:13
Fixed via 9ee2ee6.

**Comment by North-West-Wind** [comment] 2022-04-18 00:51
No it isn't. I have Discord Canary 0.0.135 on my Gentoo Linux installed via downloading directly from Discord and BD 1.5.3. Every time when Discord autostarts on boot, the injection is broken.

This might be due to the client having an update.

**Comment by alsoGAMER** [comment] 2022-04-18 00:52
Every time that updates the modules, you've to reinject it.

**Closed** 2022-04-23 04:24 UTC
Labels: bug
