### ISSUE TITLE
[Bug] Custom CSS Not Opening After I Click On It

### ISSUE THREAD

**Issue by BlazeRunner253** [BetterDiscord/BetterDiscord#961] opened 2021-07-27 15:22 UTC
Recently i tried to open the custom CSS tab in my BetterDiscord, however it just doesn't open !
I keep on trying to open the tab over and over again, but it shows no sign of opening, thus i cannot my CSS editor

I have deleted and downloaded the BetterDiscord application twice, however it still doesn't fix the issue.
 It would be very helpful if someone guides me in fixing this issue.

**Comment by dav1312** [comment] 2021-07-27 15:22
Duplicate of #949

**Closed** 2021-07-27 17:20 UTC
Labels: bug
