### ISSUE TITLE
[Bug] Discord Soundboard feature unavailable

### ISSUE THREAD

**Issue by DownloadingRam** [BetterDiscord/BetterDiscord#1606] opened 2023-04-10 01:58 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

The new Soundboard feature is not available in either the server settings menu or underneath the current call display

### Expected Behavior

The feature is there upon removing BetterDiscord, and disappears once installed
![image](https://user-images.githubusercontent.com/49964900/230810325-5febce1c-9de6-4186-a97b-60cf0aa97c46.png)

### Steps To Reproduce

1: Install BetterDiscord
2: No Soundboard
3: :shrug

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

1.0.9012

**Comment by maenDisease** [comment] 2023-04-10 02:04
I cannot replicate this issue

**Comment by DownloadingRam** [comment] 2023-04-10 02:24
This is what my discord looks like without BetterDiscord
![image](https://user-images.githubusercontent.com/49964900/230812272-9dfda4e1-5ef2-4bf8-9528-83bf7d3aaa1f.png)
And after installing version 1.9.2(The previous update version I mention was incorrect) on the latest installer (1.2.1), it looks like this:
![image](https://user-images.githubusercontent.com/49964900/230812628-743b1b8c-1bb4-479c-9b22-bc52ef201d31.png)
The menu inside the "Server Settings" tab has also disappeared

**Comment by DownloadingRam** [comment] 2023-04-10 02:27
Upon using the repair tool, the problem seems to have fixed itself. I have uninstalled and reinstalled 3-4 times so I'm not sure why a repair fixes it, but I'll leave this here in case.

**Comment by Ya-boy-Jotaro-KuJo** [comment] 2023-04-11 09:35
> Upon using the repair tool, the problem seems to have fixed itself. I have uninstalled and reinstalled 3-4 times so I'm not sure why a repair fixes it, but I'll leave this here in case.

repair disables plugins and also close the issue

**Closed** 2023-04-11 09:38 UTC
Labels: bug

**Comment by slysnake96** [comment] 2023-05-04 19:15
The plugin called DiscordBypasses created by Tharki-God was the cause for me, once I disabled that the soundboard options finally showed up for me.
