### ISSUE TITLE
[Bug] Custom CSS window not opening

### ISSUE THREAD

**Issue by TheChilliPL** [BetterDiscord/BetterDiscord#963] opened 2021-07-27 18:58 UTC
**Describe the Bug**
Custom CSS button in settings does nothing.

**To Reproduce**
1. Open settings.
2. Try opening `Custom CSS` window using the button on the sidebar.

**Expected Behavior**
Custom CSS window should appear.

**Screenshots**

**Discord Version**

Stable 91289
BetterDiscord 1.2.0
Host 1.0.9002

**Additional Context**

**Comment by rauenzi** [comment] 2021-07-27 19:01
Duplicate of #949

**Closed by rauenzi** 2021-07-27 19:01 UTC
Labels: bug
