### ISSUE TITLE
BetterDiscord crashes whenever someone switches from one window to another while I'm watching it [Bug]

### ISSUE THREAD

**Issue by Icesolate** [BetterDiscord/BetterDiscord#878] opened 2021-07-08 02:47 UTC
Whenever I am watching one of my friends stream a game like League of Legends where the window switches from client to in-game, my Discord will crash and show the message that "Better Discord seems to have crashed your Discord client."

I have looked at previous bug reports of similar caliber, but none of the solutions seem to have worked. I have removed plugins and themes, re-installed BD, and the same error message pops up. Even when I have no themes or plugins, my Discord will still crash. It doesn't seem to crash when someone switches from one Google Chrome window to another.

I am using the standard stable Discord version.

![image](https://user-images.githubusercontent.com/87106353/124854384-3fd4a400-df75-11eb-851a-e0a1f884578f.png)

**Comment by LiefAmai** [comment] 2021-07-08 06:48
Yeah, having the same issue here. Disabling all my plugins does nothing, disabling or enabling themes does nothing. Reinstalling BetterDiscord does nothing... Started happening a few days ago.

**Comment by dav1312** [comment] 2021-07-08 10:39
Duplicate of #861

**Closed** 2021-07-09 22:29 UTC
Labels: bug
