### ISSUE TITLE
[Bug] BetterDiscord Update Loop!

### ISSUE THREAD

**Issue by StrikerFNOnYT** [BetterDiscord/BetterDiscord#1350] opened 2022-08-01 11:21 UTC
**Describe the Bug**

So it says "Update Available" So I click on Update Now and then Restart Now, after I restart it, it says again "Update Available"

**To Reproduce**

**Expected Behavior**
 
I expected that it wouldn't ask me to update it again after I did the update.

**Screenshots**

<img width="235" alt="image" src="https://user-images.githubusercontent.com/98457448/182137306-994be688-cf1a-48d5-a158-a4f9ec73d6d9.png">

**Discord Version**

**Additional Context**

Nope.

**Comment by StrikerFNOnYT** [comment] 2022-08-01 11:22
My Discord Verison Was v1.5.3

**Comment by ItMeSarah** [comment] 2022-08-01 11:22
Known issue. Update once and then click Skip the next time you get it, you'll have to do that until the issue is fixed.

**Comment by StrikerFNOnYT** [comment] 2022-08-01 11:23
Thanks for the quick response, I was thinking it was gonna take a day or two.

**Comment by SpotlightForBugs** [comment] 2022-08-01 11:27
I have the same issue

**Comment by SmolAlli** [comment] 2022-08-01 11:28
Also a duplicate of #1349. Please look at what is open before opening an issue.

**Closed** 2022-08-05 04:12 UTC
Labels: bug
