### ISSUE TITLE
BetterDiscord crashed whenever the emoji button or other option is used in text bar [Bug]

### ISSUE THREAD

**Issue by SdkKKK** [BetterDiscord/BetterDiscord#1128] opened 2021-11-14 15:34 UTC
So I had this same issue with the discord crashing in every try to use the emoji menu or any other option in the text bar,
![ScreenShot_20211114214131](https://user-images.githubusercontent.com/59328642/141688006-7cc38308-a0a0-4327-a8ef-3f1c0cc1961d.png)

![ScreenShot_20211114214145](https://user-images.githubusercontent.com/59328642/141688010-28d525ab-1e67-4c2d-a5f7-85a04e6136ff.png)

 I found a solution to this.

Here's the instruction.

go to C:\Users\ _____ \AppData\Roaming\BetterDiscord\data\stable

(if you can't find it then use this method)

Win+R > %appdata% > BetterDiscord > data > stable

Then open emotes.json and you will see this ( "emoteMenu": true, ) you have to change it into "false"  then save the file and restart discord.

If this was difficult to understand then download the file from the link down below and just paste it into the stable file where the emotes.json file is located.

[https://drive.google.com/file/d/1EYSXzrowcFdzOvvVQAWkqzByfMdgFj3o/view?usp=sharing](url)

Then restart discord.

You're good to go.

I edited this several times because I was having issue just showing the full text file here so I uploaded that whole .json file into my google drive.

I will close this report later.

**Comment by TheGreenPig** [comment] 2021-11-14 15:35
Duplicate of #1116

**Comment by SdkKKK** [comment] 2021-11-14 16:17
> Duplicate of #1116
> 
> Edit: why did you mention rauenzi? He is well aware of the issue and a fix was already made that will be pushed soon...

Sorry, then i'll remove the mention right away.

**Comment by rauenzi** [comment] 2021-11-14 17:07
You've already done the mention, removing it does nothing

**Closed** 2021-11-14 17:07 UTC
Labels: bug
