### ISSUE TITLE
[Bug] BetterDiscord consistently crashes between 5-25 hours after startup

### ISSUE THREAD

**Issue by k4zo** [BetterDiscord/BetterDiscord#1381] opened 2022-08-24 03:55 UTC
**Describe the Bug**
Depending on how many plugins are installed/loaded, BetterDiscord consistently builds up lag and crashes every 5 hr-1 day for seemingly no reason

**To Reproduce**
-Use BetterDiscord
-Have a normal amount of plugins
-Watch as BD crashes at least once a day

**Expected Behavior**
-Use BD
-It doesn't crash at least once a day

**Screenshots**
https://imgur.com/BBJMrY1

**Discord Version**
Stable

**Additional Context**
Ignore the window border in the screenshot, the issue happened just as often when I used Windows 10
Resubmit because my first issue on the same topic from a few months ago is flooded out and hasn't been fixed despite countless people exhibiting the same issue
Also this issue went from happening to about 2-3 times a week to multiple times a day now despite me not adding any plugins

**Comment by SmolAlli** [comment] 2022-08-24 03:56
This is more an issue with the plugins and the resources they take up, and is not an issue for this repository.

**Comment by ImDini** [comment] 2022-08-24 07:39
> This is more an issue with the plugins and the resources they take up, and is not an issue for this repository.

I have the same issue and have a very few select plugins. Tried disabling them, it's not the plugins. It's better discord.

**Comment by Ativ3k** [comment] 2022-08-26 18:22
i agree, after few hours (sometimes minutes) without plugins/themes betterdiscord using +1GB RAM and crash

**Comment by PinguLinux** [comment] 2022-08-29 19:03
i have this same issue and i thought it was because some plugin

**Comment by rauenzi** [comment] 2022-08-31 15:10
Self-admitted duplicate of #859

**Closed by rauenzi** 2022-08-31 15:10 UTC
Labels: bug
