### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LaShids** [BetterDiscord/BetterDiscord#1188] opened 2022-01-30 02:19 UTC
**Describe the Bug**
Window doesnt snap to the side when "Enable Transparency" turned on

**To Reproduce**
Turn on the "Enable Transparency" setting and move window to any side of the screen

**Discord Version**
Stable 112515 (900f57b)
BetterDiscord 1.4.0

**Comment by TheCommieAxolotl** [comment] 2022-01-30 02:22
Duplicate of #1140

**Closed** 2022-01-30 04:14 UTC
Labels: bug
