### ISSUE TITLE
Better discord stop working [Bug]

### ISSUE THREAD

**Issue by SamKittens** [BetterDiscord/BetterDiscord#1218] opened 2022-02-16 01:36 UTC
**Describe the Bug**
 I was using discord when suddenly it restarted, by doing this better discord stopped working, try to reinstall better discord, repair it, delete it and put it back and nothing, it doesn't work

**Discord Version**

**Comment by Inve1951** [comment] 2022-02-16 01:37
Duplicate of #1216.

**Closed by Inve1951** 2022-02-16 01:37 UTC
Labels: bug

**Comment by FireTonnor** [comment] 2022-02-16 01:41
⚠️ A Discord update has broken BD on all platforms and across all release channels. Expect an update soon but be patient.  ⚠️
